# Run Rich Multimodal Branch

This notebook runs only the final OCR + BLIP + BERT + ResNet50 enriched fusion branch from `03_Multimodal_Model_Training_FINAL_Enhanced.ipynb`.

It uses the existing train/validation/test-safe design from Notebook 03 and writes outputs to `final_artifacts/`.

If cached rich features already exist, it runs quickly. To force full OCR/BLIP feature extraction again, set `RICH_FORCE_REBUILD_FEATURES = True` inside the rich branch cell in Notebook 03 before running this notebook.

In [1]:
from pathlib import Path
import nbformat
from IPython.display import display

NOTEBOOK_03 = Path('03_Multimodal_Model_Training_FINAL_Enhanced.ipynb')
FINAL_ARTIFACT_DIR = Path('final_artifacts')
FINAL_ARTIFACT_DIR.mkdir(exist_ok=True)

print('Notebook 03 exists:', NOTEBOOK_03.exists())
print('Artifact directory:', FINAL_ARTIFACT_DIR.resolve())

Notebook 03 exists: True
Artifact directory: D:\DM\DL\Deep-learning-Multimodal\final_artifacts

In [2]:
nb = nbformat.read(NOTEBOOK_03, as_version=4)
required_markers = [
    '# FINAL UPGRADE 03-M1',
    '# FINAL UPGRADE 03-M2',
    '# FINAL UPGRADE 03-M3',
    '# FINAL UPGRADE 03-M4',
    '# FINAL UPGRADE 03-M7',
    '# FINAL UPGRADE 03-M6',
]

cells_to_run = []
for marker in required_markers:
    for idx, cell in enumerate(nb.cells):
        if cell.cell_type == 'code' and marker in cell.source:
            cells_to_run.append((idx, marker, cell.source))
            break
    else:
        raise RuntimeError(f'Could not find required cell marker: {marker}')

for idx, marker, _ in cells_to_run:
    print(f'Found {marker} at Notebook 03 cell {idx}')

Found # FINAL UPGRADE 03-M1 at Notebook 03 cell 50
Found # FINAL UPGRADE 03-M2 at Notebook 03 cell 52
Found # FINAL UPGRADE 03-M3 at Notebook 03 cell 54
Found # FINAL UPGRADE 03-M4 at Notebook 03 cell 56
Found # FINAL UPGRADE 03-M7 at Notebook 03 cell 59
Found # FINAL UPGRADE 03-M6 at Notebook 03 cell 60

In [3]:
# Run the selected Notebook 03 cells in order.
# This keeps Notebook 03 as the source of truth while giving you an .ipynb runner.

namespace = globals()
for idx, marker, source in cells_to_run:
    print(f'\n===== RUNNING Notebook 03 cell {idx}: {marker} =====')
    exec(compile(source, f'{NOTEBOOK_03.name}:cell-{idx}', 'exec'), namespace)
    print(f'===== FINISHED Notebook 03 cell {idx}: {marker} =====')

print('\nRich multimodal notebook run finished.')

===== RUNNING Notebook 03 cell 50: # FINAL UPGRADE 03-M1 =====
Dataset / Split Summary

,split,file,rows,fake,real,valid_images,valid_image_coverage_%,id_column,title_column,image_column,label_column,source_column
0,train,data_splits\train_valid_images_only_image_dele...,4829,2320,2509,4829,100.0,id,title,image_path_primary,label_id,source
1,validation,data_splits\val_valid_images_only_image_deleak...,541,250,291,541,100.0,id,title,image_path_primary,label_id,source
2,test,data_splits\test_valid_images_only_image_delea...,518,230,288,518,100.0,id,title,image_path_primary,label_id,source

       source  test_rows
0   gossipcop        509
1  politifact          9

,file,has_prob_fake,columns
0,concat_fusion_cnn+text_test_predictions_seed12...,True,"id, source, title, label, valid_image_path, im..."
1,concat_fusion_cnn+text_test_predictions_seed20...,True,"id, source, title, label, valid_image_path, im..."
2,concat_fusion_cnn+text_test_predictions_seed42...,True,"id, source, title, label, valid_image_path, im..."
3,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
4,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
5,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
6,final_clip_best_test_predictions.csv,True,"id, source, title, label, valid_image_path, im..."
7,final_text_bert_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."
8,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
9,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
10,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
11,image-only_cnn_test_predictions_seed123.csv,True,"id, source, title, label, valid_image_path, im..."
12,image-only_cnn_test_predictions_seed2026.csv,True,"id, source, title, label, valid_image_path, im..."
13,image-only_cnn_test_predictions_seed42.csv,True,"id, source, title, label, valid_image_path, im..."
14,late_fusion_test_predictions.csv,True,"id, title, label, label_id, valid_image_path, ..."
15,rich_multimodal_test_predictions.csv,True,"id, label, source, title, image_path_primary, ..."
16,text_tfidf_final_deleaked_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."
17,text_transformer_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."

===== FINISHED Notebook 03 cell 50: # FINAL UPGRADE 03-M1 =====

===== RUNNING Notebook 03 cell 52: # FINAL UPGRADE 03-M2 =====
Reused existing transformer text predictions: final_artifacts\final_text_bert_test_predictions.csv

,model,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc
0,Transformer text classifier (reused existing D...,0.752896,0.7511,0.750494,0.752823,0.772242,0.729958,0.835537,0.773909

===== FINISHED Notebook 03 cell 52: # FINAL UPGRADE 03-M2 =====

===== RUNNING Notebook 03 cell 54: # FINAL UPGRADE 03-M3 =====
Reused existing CLIP score file: final_artifacts\clip_inconsistency_test_scores.csv

,valid_image_text_pairs,mean_clip_similarity_real,mean_clip_similarity_fake,mean_inconsistency_real,mean_inconsistency_fake,real_minus_fake_similarity_gap,clip_inconsistency_roc_auc,clip_inconsistency_pr_auc,welch_ttest_p_value,cohens_d_real_minus_fake_similarity
0,492,0.308808,0.319455,0.315427,0.283676,-0.010647,0.436645,0.409897,0.012013,-0.22616

===== FINISHED Notebook 03 cell 54: # FINAL UPGRADE 03-M3 =====

===== RUNNING Notebook 03 cell 56: # FINAL UPGRADE 03-M4 =====
Added image-only test probability for descriptive test table from: image-only_cnn_test_predictions_seed123.csv

,model,best_validation_threshold,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc
0,Late fusion: text probability + CLIP consistency,0.505,0.762548,0.760224,0.759666,0.761066,0.783831,0.736617,0.830088,0.80955

===== FINISHED Notebook 03 cell 56: # FINAL UPGRADE 03-M4 =====

===== RUNNING Notebook 03 cell 59: # FINAL UPGRADE 03-M7 =====

d:\DM\DL\Deep-learning-Multimodal\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Rich fusion device: cuda

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17356.70it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 473/473 [00:00<00:00, 70568.98it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Using text encoder: bert-base-uncased; feature dim=4352
Loaded cached rich features for train: (4829, 4352)
Loaded cached rich features for val: (541, 4352)
Loaded cached rich features for test: (518, 4352)
Rich fusion epoch=1: val macro-F1=0.5602, val ROC-AUC=0.6269
Rich fusion epoch=2: val macro-F1=0.5845, val ROC-AUC=0.6250
Rich fusion epoch=3: val macro-F1=0.6061, val ROC-AUC=0.6643
Rich fusion epoch=4: val macro-F1=0.6389, val ROC-AUC=0.6696
Rich fusion epoch=5: val macro-F1=0.6530, val ROC-AUC=0.6745
Rich fusion epoch=6: val macro-F1=0.6392, val ROC-AUC=0.6861
Rich fusion epoch=7: val macro-F1=0.6431, val ROC-AUC=0.6753
Rich fusion epoch=8: val macro-F1=0.6570, val ROC-AUC=0.6947
Rich fusion epoch=9: val macro-F1=0.6442, val ROC-AUC=0.6849
Rich fusion epoch=10: val macro-F1=0.6385, val ROC-AUC=0.6766
Rich fusion epoch=11: val macro-F1=0.6549, val ROC-AUC=0.6905
Rich fusion early stopping at epoch 11; best epoch=8.

,model,input,best_epoch,best_validation_threshold,n_test,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc,notes
0,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 image + OCR BERT + ...,8,0.52,518,0.671815,0.670222,0.670426,0.672464,0.693141,0.647303,0.702582,0.616338,Frozen pretrained feature extractors; MLP trai...

===== FINISHED Notebook 03 cell 59: # FINAL UPGRADE 03-M7 =====

===== RUNNING Notebook 03 cell 60: # FINAL UPGRADE 03-M6 =====
Fake/Real Classification Results

,Model,Input,Accuracy,Macro-F1,Precision Macro,Recall Macro,ROC-AUC,PR-AUC,Notes
0,Majority baseline,Title text only,0.555985,0.357320,0.277992,0.500000,NaN,NaN,Final de-leaked test split.
1,Text-only TF-IDF + Logistic Regression,Title text only,0.760618,0.757579,0.757579,0.757579,0.830299,0.809707,Recomputed on final de-leaked split; no source...
2,Transformer text classifier,Title text only,0.752896,0.751100,0.750494,0.752823,0.835537,0.773909,Reused existing aligned DistilBERT artifact.
3,Concat fusion CNN+Text,Image/text according to ablation,0.760618,0.757357,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
4,Consistency fusion CNN+Text,Image/text according to ablation,0.763192,0.760846,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
5,Frozen ResNet50 fusion CNN+Text,Image/text according to ablation,0.749678,0.746826,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
6,Image-only CNN,Image/text according to ablation,0.558559,0.554441,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
7,Late fusion: text probability + CLIP consistency,Text probability + CLIP features + valid-image...,0.762548,0.760224,0.759666,0.761066,0.830088,0.809550,Threshold tuned on validation split.
8,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 + OCR BERT + BLIP-c...,0.671815,0.670222,0.670426,0.672464,0.702582,0.616338,Optional rich frozen-feature branch; train/val...
9,CLIP inconsistency alone as score-only detector,Image-title CLIP similarity only,NaN,NaN,NaN,NaN,0.436645,0.409897,"Proxy consistency score, not direct fake-news ..."

Image-Text Consistency Analysis

,Metric,Value,Interpretation
0,Valid image-text pairs,492.000000,Rows with usable title and image for CLIP scor...
1,"Mean CLIP similarity, real",0.308808,Average image-title alignment among real-label...
2,"Mean CLIP similarity, fake",0.319455,Average image-title alignment among fake-label...
3,Gap: real minus fake,-0.010647,Positive means real articles are more aligned ...
4,"Mean inconsistency, real",0.315427,Average 1-normalized-similarity for real-label...
5,"Mean inconsistency, fake",0.283676,Average 1-normalized-similarity for fake-label...
6,CLIP inconsistency ROC-AUC,0.436645,Fake/real ranking by inconsistency proxy; 0.5 ...
7,CLIP inconsistency PR-AUC,0.409897,Average precision for fake class using inconsi...
8,Welch t-test p-value,0.012013,"Difference in mean similarity, not ground-trut..."
9,Cohen's d,-0.226160,Effect size for real-vs-fake similarity differ...

Why CLIP Alone Is Not Enough

,Case Type,Example Group,Interpretation,What It Shows
0,Fake + high CLIP similarity,A,The image and title appear semantically aligne...,CLIP alone cannot verify factual truth.
1,Fake + low CLIP similarity,B,The article is fake and the image-title pair i...,Potential visual inconsistency or out-of-conte...
2,Real + low CLIP similarity,C,The label is real but CLIP similarity is low.,"Generic images, weak titles, noisy images, or ..."
3,Real + high CLIP similarity,D,The article is real and the image-title pair i...,"A clean aligned case, useful as a sanity check."

===== FINISHED Notebook 03 cell 60: # FINAL UPGRADE 03-M6 =====

Rich multimodal notebook run finished.

In [4]:
import pandas as pd

for path in [
    FINAL_ARTIFACT_DIR / 'rich_multimodal_metrics.csv',
    FINAL_ARTIFACT_DIR / 'report_table_classification_results.csv',
]:
    print('\n', path)
    if path.exists():
        display(pd.read_csv(path))
    else:
        print('Missing')

 final_artifacts\rich_multimodal_metrics.csv

,model,input,best_epoch,best_validation_threshold,n_test,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc,notes
0,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 image + OCR BERT + ...,8,0.52,518,0.671815,0.670222,0.670426,0.672464,0.693141,0.647303,0.702582,0.616338,Frozen pretrained feature extractors; MLP trai...

 final_artifacts\report_table_classification_results.csv

,Model,Input,Accuracy,Macro-F1,Precision Macro,Recall Macro,ROC-AUC,PR-AUC,Notes
0,Majority baseline,Title text only,0.555985,0.357320,0.277992,0.500000,NaN,NaN,Final de-leaked test split.
1,Text-only TF-IDF + Logistic Regression,Title text only,0.760618,0.757579,0.757579,0.757579,0.830299,0.809707,Recomputed on final de-leaked split; no source...
2,Transformer text classifier,Title text only,0.752896,0.751100,0.750494,0.752823,0.835537,0.773909,Reused existing aligned DistilBERT artifact.
3,Concat fusion CNN+Text,Image/text according to ablation,0.760618,0.757357,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
4,Consistency fusion CNN+Text,Image/text according to ablation,0.763192,0.760846,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
5,Frozen ResNet50 fusion CNN+Text,Image/text according to ablation,0.749678,0.746826,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
6,Image-only CNN,Image/text according to ablation,0.558559,0.554441,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
7,Late fusion: text probability + CLIP consistency,Text probability + CLIP features + valid-image...,0.762548,0.760224,0.759666,0.761066,0.830088,0.809550,Threshold tuned on validation split.
8,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 + OCR BERT + BLIP-c...,0.671815,0.670222,0.670426,0.672464,0.702582,0.616338,Optional rich frozen-feature branch; train/val...
9,CLIP inconsistency alone as score-only detector,Image-title CLIP similarity only,NaN,NaN,NaN,NaN,0.436645,0.409897,"Proxy consistency score, not direct fake-news ..."