# Rich Multimodal, Hard-Sample, and Final Retraining Experiments

Preserves the rich OCR/BLIP branch, GT6 filtering experiment, and final hard-sample-cleaned normal-split retraining notebook.

---

## Original Source: `05_Run_Rich_Multimodal_Branch.ipynb`

The following cells are preserved from the original notebook during GitHub reorganization.

# Run Rich Multimodal Branch

This notebook runs only the final OCR + BLIP + BERT + ResNet50 enriched fusion branch from `03_Multimodal_Model_Training_FINAL_Enhanced.ipynb`.

It uses the existing train/validation/test-safe design from Notebook 03 and writes outputs to `final_artifacts/`.

If cached rich features already exist, it runs quickly. To force full OCR/BLIP feature extraction again, set `RICH_FORCE_REBUILD_FEATURES = True` inside the rich branch cell in Notebook 03 before running this notebook.

In [1]:
from pathlib import Path
import nbformat
from IPython.display import display

NOTEBOOK_03 = Path('03_Multimodal_Model_Training_FINAL_Enhanced.ipynb')
FINAL_ARTIFACT_DIR = Path('final_artifacts')
FINAL_ARTIFACT_DIR.mkdir(exist_ok=True)

print('Notebook 03 exists:', NOTEBOOK_03.exists())
print('Artifact directory:', FINAL_ARTIFACT_DIR.resolve())

Notebook 03 exists: True
Artifact directory: D:\DM\DL\Deep-learning-Multimodal\final_artifacts

In [2]:
nb = nbformat.read(NOTEBOOK_03, as_version=4)
required_markers = [
    '# FINAL UPGRADE 03-M1',
    '# FINAL UPGRADE 03-M2',
    '# FINAL UPGRADE 03-M3',
    '# FINAL UPGRADE 03-M4',
    '# FINAL UPGRADE 03-M7',
    '# FINAL UPGRADE 03-M6',
]

cells_to_run = []
for marker in required_markers:
    for idx, cell in enumerate(nb.cells):
        if cell.cell_type == 'code' and marker in cell.source:
            cells_to_run.append((idx, marker, cell.source))
            break
    else:
        raise RuntimeError(f'Could not find required cell marker: {marker}')

for idx, marker, _ in cells_to_run:
    print(f'Found {marker} at Notebook 03 cell {idx}')

Found # FINAL UPGRADE 03-M1 at Notebook 03 cell 50
Found # FINAL UPGRADE 03-M2 at Notebook 03 cell 52
Found # FINAL UPGRADE 03-M3 at Notebook 03 cell 54
Found # FINAL UPGRADE 03-M4 at Notebook 03 cell 56
Found # FINAL UPGRADE 03-M7 at Notebook 03 cell 59
Found # FINAL UPGRADE 03-M6 at Notebook 03 cell 60

In [3]:
# Run the selected Notebook 03 cells in order.
# This keeps Notebook 03 as the source of truth while giving you an .ipynb runner.

namespace = globals()
for idx, marker, source in cells_to_run:
    print(f'\n===== RUNNING Notebook 03 cell {idx}: {marker} =====')
    exec(compile(source, f'{NOTEBOOK_03.name}:cell-{idx}', 'exec'), namespace)
    print(f'===== FINISHED Notebook 03 cell {idx}: {marker} =====')

print('\nRich multimodal notebook run finished.')

===== RUNNING Notebook 03 cell 50: # FINAL UPGRADE 03-M1 =====
Dataset / Split Summary

,split,file,rows,fake,real,valid_images,valid_image_coverage_%,id_column,title_column,image_column,label_column,source_column
0,train,data_splits\train_valid_images_only_image_dele...,4829,2320,2509,4829,100.0,id,title,image_path_primary,label_id,source
1,validation,data_splits\val_valid_images_only_image_deleak...,541,250,291,541,100.0,id,title,image_path_primary,label_id,source
2,test,data_splits\test_valid_images_only_image_delea...,518,230,288,518,100.0,id,title,image_path_primary,label_id,source

       source  test_rows
0   gossipcop        509
1  politifact          9

,file,has_prob_fake,columns
0,concat_fusion_cnn+text_test_predictions_seed12...,True,"id, source, title, label, valid_image_path, im..."
1,concat_fusion_cnn+text_test_predictions_seed20...,True,"id, source, title, label, valid_image_path, im..."
2,concat_fusion_cnn+text_test_predictions_seed42...,True,"id, source, title, label, valid_image_path, im..."
3,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
4,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
5,consistency_fusion_cnn+text_test_predictions_s...,True,"id, source, title, label, valid_image_path, im..."
6,final_clip_best_test_predictions.csv,True,"id, source, title, label, valid_image_path, im..."
7,final_text_bert_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."
8,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
9,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
10,frozen_resnet50_fusion_cnn+text_test_predictio...,True,"id, source, title, label, valid_image_path, im..."
11,image-only_cnn_test_predictions_seed123.csv,True,"id, source, title, label, valid_image_path, im..."
12,image-only_cnn_test_predictions_seed2026.csv,True,"id, source, title, label, valid_image_path, im..."
13,image-only_cnn_test_predictions_seed42.csv,True,"id, source, title, label, valid_image_path, im..."
14,late_fusion_test_predictions.csv,True,"id, title, label, label_id, valid_image_path, ..."
15,rich_multimodal_test_predictions.csv,True,"id, label, source, title, image_path_primary, ..."
16,text_tfidf_final_deleaked_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."
17,text_transformer_test_predictions.csv,True,"id, source, title, label, valid_image_path, pr..."

===== FINISHED Notebook 03 cell 50: # FINAL UPGRADE 03-M1 =====

===== RUNNING Notebook 03 cell 52: # FINAL UPGRADE 03-M2 =====
Reused existing transformer text predictions: final_artifacts\final_text_bert_test_predictions.csv

,model,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc
0,Transformer text classifier (reused existing D...,0.752896,0.7511,0.750494,0.752823,0.772242,0.729958,0.835537,0.773909

===== FINISHED Notebook 03 cell 52: # FINAL UPGRADE 03-M2 =====

===== RUNNING Notebook 03 cell 54: # FINAL UPGRADE 03-M3 =====
Reused existing CLIP score file: final_artifacts\clip_inconsistency_test_scores.csv

,valid_image_text_pairs,mean_clip_similarity_real,mean_clip_similarity_fake,mean_inconsistency_real,mean_inconsistency_fake,real_minus_fake_similarity_gap,clip_inconsistency_roc_auc,clip_inconsistency_pr_auc,welch_ttest_p_value,cohens_d_real_minus_fake_similarity
0,492,0.308808,0.319455,0.315427,0.283676,-0.010647,0.436645,0.409897,0.012013,-0.22616

===== FINISHED Notebook 03 cell 54: # FINAL UPGRADE 03-M3 =====

===== RUNNING Notebook 03 cell 56: # FINAL UPGRADE 03-M4 =====
Added image-only test probability for descriptive test table from: image-only_cnn_test_predictions_seed123.csv

,model,best_validation_threshold,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc
0,Late fusion: text probability + CLIP consistency,0.505,0.762548,0.760224,0.759666,0.761066,0.783831,0.736617,0.830088,0.80955

===== FINISHED Notebook 03 cell 56: # FINAL UPGRADE 03-M4 =====

===== RUNNING Notebook 03 cell 59: # FINAL UPGRADE 03-M7 =====

d:\DM\DL\Deep-learning-Multimodal\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Rich fusion device: cuda

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17356.70it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 473/473 [00:00<00:00, 70568.98it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Using text encoder: bert-base-uncased; feature dim=4352
Loaded cached rich features for train: (4829, 4352)
Loaded cached rich features for val: (541, 4352)
Loaded cached rich features for test: (518, 4352)
Rich fusion epoch=1: val macro-F1=0.5602, val ROC-AUC=0.6269
Rich fusion epoch=2: val macro-F1=0.5845, val ROC-AUC=0.6250
Rich fusion epoch=3: val macro-F1=0.6061, val ROC-AUC=0.6643
Rich fusion epoch=4: val macro-F1=0.6389, val ROC-AUC=0.6696
Rich fusion epoch=5: val macro-F1=0.6530, val ROC-AUC=0.6745
Rich fusion epoch=6: val macro-F1=0.6392, val ROC-AUC=0.6861
Rich fusion epoch=7: val macro-F1=0.6431, val ROC-AUC=0.6753
Rich fusion epoch=8: val macro-F1=0.6570, val ROC-AUC=0.6947
Rich fusion epoch=9: val macro-F1=0.6442, val ROC-AUC=0.6849
Rich fusion epoch=10: val macro-F1=0.6385, val ROC-AUC=0.6766
Rich fusion epoch=11: val macro-F1=0.6549, val ROC-AUC=0.6905
Rich fusion early stopping at epoch 11; best epoch=8.

,model,input,best_epoch,best_validation_threshold,n_test,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc,notes
0,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 image + OCR BERT + ...,8,0.52,518,0.671815,0.670222,0.670426,0.672464,0.693141,0.647303,0.702582,0.616338,Frozen pretrained feature extractors; MLP trai...

===== FINISHED Notebook 03 cell 59: # FINAL UPGRADE 03-M7 =====

===== RUNNING Notebook 03 cell 60: # FINAL UPGRADE 03-M6 =====
Fake/Real Classification Results

,Model,Input,Accuracy,Macro-F1,Precision Macro,Recall Macro,ROC-AUC,PR-AUC,Notes
0,Majority baseline,Title text only,0.555985,0.357320,0.277992,0.500000,NaN,NaN,Final de-leaked test split.
1,Text-only TF-IDF + Logistic Regression,Title text only,0.760618,0.757579,0.757579,0.757579,0.830299,0.809707,Recomputed on final de-leaked split; no source...
2,Transformer text classifier,Title text only,0.752896,0.751100,0.750494,0.752823,0.835537,0.773909,Reused existing aligned DistilBERT artifact.
3,Concat fusion CNN+Text,Image/text according to ablation,0.760618,0.757357,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
4,Consistency fusion CNN+Text,Image/text according to ablation,0.763192,0.760846,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
5,Frozen ResNet50 fusion CNN+Text,Image/text according to ablation,0.749678,0.746826,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
6,Image-only CNN,Image/text according to ablation,0.558559,0.554441,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
7,Late fusion: text probability + CLIP consistency,Text probability + CLIP features + valid-image...,0.762548,0.760224,0.759666,0.761066,0.830088,0.809550,Threshold tuned on validation split.
8,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 + OCR BERT + BLIP-c...,0.671815,0.670222,0.670426,0.672464,0.702582,0.616338,Optional rich frozen-feature branch; train/val...
9,CLIP inconsistency alone as score-only detector,Image-title CLIP similarity only,NaN,NaN,NaN,NaN,0.436645,0.409897,"Proxy consistency score, not direct fake-news ..."

Image-Text Consistency Analysis

,Metric,Value,Interpretation
0,Valid image-text pairs,492.000000,Rows with usable title and image for CLIP scor...
1,"Mean CLIP similarity, real",0.308808,Average image-title alignment among real-label...
2,"Mean CLIP similarity, fake",0.319455,Average image-title alignment among fake-label...
3,Gap: real minus fake,-0.010647,Positive means real articles are more aligned ...
4,"Mean inconsistency, real",0.315427,Average 1-normalized-similarity for real-label...
5,"Mean inconsistency, fake",0.283676,Average 1-normalized-similarity for fake-label...
6,CLIP inconsistency ROC-AUC,0.436645,Fake/real ranking by inconsistency proxy; 0.5 ...
7,CLIP inconsistency PR-AUC,0.409897,Average precision for fake class using inconsi...
8,Welch t-test p-value,0.012013,"Difference in mean similarity, not ground-trut..."
9,Cohen's d,-0.226160,Effect size for real-vs-fake similarity differ...

Why CLIP Alone Is Not Enough

,Case Type,Example Group,Interpretation,What It Shows
0,Fake + high CLIP similarity,A,The image and title appear semantically aligne...,CLIP alone cannot verify factual truth.
1,Fake + low CLIP similarity,B,The article is fake and the image-title pair i...,Potential visual inconsistency or out-of-conte...
2,Real + low CLIP similarity,C,The label is real but CLIP similarity is low.,"Generic images, weak titles, noisy images, or ..."
3,Real + high CLIP similarity,D,The article is real and the image-title pair i...,"A clean aligned case, useful as a sanity check."

===== FINISHED Notebook 03 cell 60: # FINAL UPGRADE 03-M6 =====

Rich multimodal notebook run finished.

In [4]:
import pandas as pd

for path in [
    FINAL_ARTIFACT_DIR / 'rich_multimodal_metrics.csv',
    FINAL_ARTIFACT_DIR / 'report_table_classification_results.csv',
]:
    print('\n', path)
    if path.exists():
        display(pd.read_csv(path))
    else:
        print('Missing')

 final_artifacts\rich_multimodal_metrics.csv

,model,input,best_epoch,best_validation_threshold,n_test,accuracy,macro_f1,precision_macro,recall_macro,real_f1,fake_f1,roc_auc,pr_auc,notes
0,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 image + OCR BERT + ...,8,0.52,518,0.671815,0.670222,0.670426,0.672464,0.693141,0.647303,0.702582,0.616338,Frozen pretrained feature extractors; MLP trai...

 final_artifacts\report_table_classification_results.csv

,Model,Input,Accuracy,Macro-F1,Precision Macro,Recall Macro,ROC-AUC,PR-AUC,Notes
0,Majority baseline,Title text only,0.555985,0.357320,0.277992,0.500000,NaN,NaN,Final de-leaked test split.
1,Text-only TF-IDF + Logistic Regression,Title text only,0.760618,0.757579,0.757579,0.757579,0.830299,0.809707,Recomputed on final de-leaked split; no source...
2,Transformer text classifier,Title text only,0.752896,0.751100,0.750494,0.752823,0.835537,0.773909,Reused existing aligned DistilBERT artifact.
3,Concat fusion CNN+Text,Image/text according to ablation,0.760618,0.757357,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
4,Consistency fusion CNN+Text,Image/text according to ablation,0.763192,0.760846,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
5,Frozen ResNet50 fusion CNN+Text,Image/text according to ablation,0.749678,0.746826,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
6,Image-only CNN,Image/text according to ablation,0.558559,0.554441,NaN,NaN,NaN,NaN,Mean across seeds from saved deep ablation res...
7,Late fusion: text probability + CLIP consistency,Text probability + CLIP features + valid-image...,0.762548,0.760224,0.759666,0.761066,0.830088,0.809550,Threshold tuned on validation split.
8,OCR+BLIP+BERT+ResNet50 enriched fusion MLP,Title/text BERT + ResNet50 + OCR BERT + BLIP-c...,0.671815,0.670222,0.670426,0.672464,0.702582,0.616338,Optional rich frozen-feature branch; train/val...
9,CLIP inconsistency alone as score-only detector,Image-title CLIP similarity only,NaN,NaN,NaN,NaN,0.436645,0.409897,"Proxy consistency score, not direct fake-news ..."

---

## Original Source: `08_Filtered_GT6_Retrain_Experiment.ipynb`

The following cells are preserved from the original notebook during GitHub reorganization.

# Filtered GT6 Hard-Sample Removal Retraining Experiment

This notebook is a **diagnostic experiment**.

It removes samples whose `wrong_multimodal_run_count > 6` from the prepared splits, then retrains the main model families to compare results before and after removing hard/ambiguous examples.

Important: because the removed samples are identified using previous test-set errors, this is **not** a fair headline benchmark. Use it as an error-analysis ablation: it tells us how much performance changes when a small hard subset is excluded.

## 1. Configuration

In [1]:
from pathlib import Path
import json
import re
import random
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')
pd.set_option('display.max_colwidth', 140)
pd.set_option('display.max_columns', 60)

SEED = 42
FILTER_THRESHOLD = 6
FILTER_COLUMN = 'wrong_multimodal_run_count'
FILTER_RULE = '>'  # your requested rule: delete samples wrong in more than 6 multimodal model runs

DATA_SPLIT_DIR = Path('data_splits')
FINAL_ARTIFACT_DIR = Path('final_artifacts')
EXPERIMENT_DIR = Path('filtered_gt6_retrain_artifacts')
FILTERED_SPLIT_DIR = DATA_SPLIT_DIR / 'filtered_gt6_multimodal_wrong_removed'

for p in [FINAL_ARTIFACT_DIR, EXPERIMENT_DIR, FILTERED_SPLIT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

LABEL_TO_ID = {'real': 0, 'fake': 1}
ID_TO_LABEL = {0: 'real', 1: 'fake'}

RUN_TEXT_TFIDF = True
RUN_DEEP_CNN_MODELS = True
RUN_FROZEN_RESNET50 = True
RUN_TEXT_BERT = True
RUN_RICH_CACHED_MLP = True
RUN_VOTING_ENSEMBLE = True

# Set lower for debugging; increase for the overnight/full run.
RETRAIN_SEEDS = [42, 123, 2026]
MAX_EPOCHS = 25
PATIENCE = 4
MIN_DELTA = 1e-4
BATCH_SIZE = 32
TEXT_MAX_FEATURES = 5000

print('Filtered retrain experiment directory:', EXPERIMENT_DIR)
print('Filtered split directory:', FILTERED_SPLIT_DIR)

Filtered retrain experiment directory: filtered_gt6_retrain_artifacts
Filtered split directory: data_splits\filtered_gt6_multimodal_wrong_removed

## 2. Build Filtered Splits

In [2]:
def load_final_split(split):
    candidates = [
        DATA_SPLIT_DIR / f'{split}_valid_images_only_image_deleaked_with_content.csv',
        DATA_SPLIT_DIR / f'{split}_valid_images_only_image_deleaked.csv',
        DATA_SPLIT_DIR / f'{split}_valid_images_only.csv',
        DATA_SPLIT_DIR / f'{split}_multimodal.csv',
        DATA_SPLIT_DIR / f'{split}.csv',
    ]
    for path in candidates:
        if path.exists():
            df = pd.read_csv(path)
            df['split'] = split
            if 'label_id' not in df.columns:
                df['label_id'] = df['label'].map(LABEL_TO_ID).astype(int)
            if 'valid_image_path' not in df.columns:
                img_col = 'image_path_primary' if 'image_path_primary' in df.columns else 'image_path'
                df['valid_image_path'] = df[img_col].fillna('').astype(str).map(lambda x: bool(x) and Path(x).exists()) if img_col in df.columns else False
            return df, path
    raise FileNotFoundError(f'No split file found for {split}. Checked: {candidates}')

hard_path = FINAL_ARTIFACT_DIR / 'final_multimodal_most_frequent_wrong_samples.csv'
if not hard_path.exists():
    raise FileNotFoundError('Run Notebook 3 voting/multimodal failure analysis first. Missing final_multimodal_most_frequent_wrong_samples.csv')

hard_df = pd.read_csv(hard_path)
if FILTER_RULE == '>':
    hard_ids = set(hard_df.loc[hard_df[FILTER_COLUMN] > FILTER_THRESHOLD, 'id'].astype(str))
else:
    hard_ids = set(hard_df.loc[hard_df[FILTER_COLUMN] >= FILTER_THRESHOLD, 'id'].astype(str))

print(f'Hard samples to remove where {FILTER_COLUMN} {FILTER_RULE} {FILTER_THRESHOLD}: {len(hard_ids)}')

split_rows = []
filtered_splits = {}
for split in ['train', 'val', 'test']:
    df, path = load_final_split(split)
    before = len(df)
    filtered = df[~df['id'].astype(str).isin(hard_ids)].reset_index(drop=True)
    filtered_splits[split] = filtered
    out_path = FILTERED_SPLIT_DIR / f'{split}.csv'
    filtered.to_csv(out_path, index=False)
    split_rows.append({
        'split': split,
        'loaded_from': str(path),
        'output_file': str(out_path),
        'rows_before': before,
        'rows_after': len(filtered),
        'rows_removed': before - len(filtered),
        'fake_after': int((filtered['label_id'] == 1).sum()),
        'real_after': int((filtered['label_id'] == 0).sum()),
    })

filter_audit = pd.DataFrame(split_rows)
filter_audit.to_csv(EXPERIMENT_DIR / 'filtered_gt6_split_audit.csv', index=False)
hard_df[hard_df['id'].astype(str).isin(hard_ids)].to_csv(EXPERIMENT_DIR / 'removed_gt6_hard_samples.csv', index=False)
display(filter_audit)

train_df = filtered_splits['train']
val_df = filtered_splits['val']
test_df = filtered_splits['test']

print('Filtered split label balance:')
display(pd.concat([
    train_df.assign(split='train'),
    val_df.assign(split='val'),
    test_df.assign(split='test'),
]).groupby(['split', 'label']).size().unstack(fill_value=0))

Hard samples to remove where wrong_multimodal_run_count > 6: 112

,split,loaded_from,output_file,rows_before,rows_after,rows_removed,fake_after,real_after
0,train,data_splits\train_valid_images_only_image_deleaked_with_content.csv,data_splits\filtered_gt6_multimodal_wrong_removed\train.csv,4829,4829,0,2320,2509
1,val,data_splits\val_valid_images_only_image_deleaked_with_content.csv,data_splits\filtered_gt6_multimodal_wrong_removed\val.csv,541,541,0,250,291
2,test,data_splits\test_valid_images_only_image_deleaked_with_content.csv,data_splits\filtered_gt6_multimodal_wrong_removed\test.csv,518,406,112,176,230

Filtered split label balance:

label  fake  real
split
test    176   230
train  2320  2509
val     250   291

## 3. Shared Metric Utilities

In [3]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_fscore_support, roc_auc_score, average_precision_score, confusion_matrix

def get_text_column(df):
    for col in ['text_for_model', 'content', 'title']:
        if col in df.columns:
            return col
    raise ValueError('No usable text column found.')

TEXT_COL = get_text_column(train_df)
print('Text column:', TEXT_COL)

def compute_metrics(y_true, y_pred, prob_fake=None, model='model'):
    y_true = np.asarray(y_true, dtype=int)
    y_pred = np.asarray(y_pred, dtype=int)
    p, r, f1, support = precision_recall_fscore_support(y_true, y_pred, labels=[0, 1], zero_division=0)
    row = {
        'model': model,
        'n_samples': int(len(y_true)),
        'accuracy': accuracy_score(y_true, y_pred),
        'macro_f1': f1_score(y_true, y_pred, average='macro', zero_division=0),
        'real_precision': p[0],
        'real_recall': r[0],
        'real_f1': f1[0],
        'fake_precision': p[1],
        'fake_recall': r[1],
        'fake_f1': f1[1],
    }
    if prob_fake is not None:
        prob = pd.to_numeric(pd.Series(prob_fake), errors='coerce')
        if prob.notna().all() and len(np.unique(y_true)) == 2:
            row['roc_auc'] = roc_auc_score(y_true, prob)
            row['pr_auc'] = average_precision_score(y_true, prob)
        else:
            row['roc_auc'] = np.nan
            row['pr_auc'] = np.nan
    else:
        row['roc_auc'] = np.nan
        row['pr_auc'] = np.nan
    return row

def save_prediction_file(df, pred_id, prob_fake, model_name):
    out = df[['id', 'source', 'title', 'label', 'label_id', 'valid_image_path']].copy()
    if 'image_path_primary' in df.columns:
        out['image_path_primary'] = df['image_path_primary']
    out['pred_id'] = np.asarray(pred_id, dtype=int)
    out['pred_label'] = [ID_TO_LABEL[int(x)] for x in pred_id]
    out['prob_fake'] = prob_fake
    out['correct'] = out['pred_id'].eq(out['label_id'].astype(int))
    safe = re.sub(r'[^A-Za-z0-9_.+-]+', '_', model_name).strip('_')
    path = EXPERIMENT_DIR / f'{safe}_test_predictions.csv'
    out.to_csv(path, index=False)
    return out, path

Text column: text_for_model

## 4. Text Baseline Retraining

In [4]:
result_rows = []
prediction_frames = []

if RUN_TEXT_TFIDF:
    from sklearn.pipeline import Pipeline
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.dummy import DummyClassifier

    X_train = train_df[TEXT_COL].fillna('').astype(str)
    X_val = val_df[TEXT_COL].fillna('').astype(str)
    X_test = test_df[TEXT_COL].fillna('').astype(str)
    y_train = train_df['label_id'].astype(int).values
    y_test = test_df['label_id'].astype(int).values

    majority = DummyClassifier(strategy='most_frequent')
    majority.fit(X_train, y_train)
    maj_pred = majority.predict(X_test)
    maj_prob = np.full(len(y_test), float(np.mean(y_train == 1)))
    result_rows.append(compute_metrics(y_test, maj_pred, maj_prob, 'Filtered GT6 Majority baseline'))
    pred_df, pred_path = save_prediction_file(test_df, maj_pred, maj_prob, 'filtered_gt6_majority')
    prediction_frames.append(pred_df.assign(model_name='filtered_gt6_majority', model_family='majority'))

    tfidf_lr = Pipeline([
        ('tfidf', TfidfVectorizer(max_features=TEXT_MAX_FEATURES, ngram_range=(1, 2), min_df=2, sublinear_tf=True)),
        ('clf', LogisticRegression(max_iter=1500, class_weight='balanced', solver='liblinear', random_state=SEED)),
    ])
    tfidf_lr.fit(X_train, y_train)
    text_pred = tfidf_lr.predict(X_test)
    text_prob = tfidf_lr.predict_proba(X_test)[:, 1]
    result_rows.append(compute_metrics(y_test, text_pred, text_prob, 'Filtered GT6 TF-IDF Logistic Regression'))
    pred_df, pred_path = save_prediction_file(test_df, text_pred, text_prob, 'filtered_gt6_tfidf_logreg')
    prediction_frames.append(pred_df.assign(model_name='filtered_gt6_tfidf_logreg', model_family='text_tfidf'))

    pd.DataFrame(result_rows).to_csv(EXPERIMENT_DIR / 'filtered_gt6_text_baseline_metrics.csv', index=False)
    display(pd.DataFrame(result_rows))

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,Filtered GT6 Majority baseline,406,0.566502,0.361635,0.566502,1.000000,0.723270,0.000000,0.000000,0.000000,0.500000,0.433498
1,Filtered GT6 TF-IDF Logistic Regression,406,0.864532,0.860740,0.860082,0.908696,0.883721,0.871166,0.806818,0.837758,0.928236,0.924338

## 5. Deep Multimodal Retraining: Image-Only, Concat, Consistency, Frozen ResNet50

In [ ]:
if RUN_DEEP_CNN_MODELS:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    from PIL import Image
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.preprocessing import StandardScaler
    from scipy import sparse
    try:
        from torchvision import transforms, models
        TORCHVISION_OK = True
    except Exception as exc:
        TORCHVISION_OK = False
        print('Torchvision unavailable; deep image models will be skipped:', repr(exc))

    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('Device:', DEVICE)

    def set_seed(seed):
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)

    vectorizer = TfidfVectorizer(max_features=TEXT_MAX_FEATURES, ngram_range=(1, 2), min_df=2, sublinear_tf=True)
    X_train_text = vectorizer.fit_transform(train_df[TEXT_COL].fillna('').astype(str))
    X_val_text = vectorizer.transform(val_df[TEXT_COL].fillna('').astype(str))
    X_test_text = vectorizer.transform(test_df[TEXT_COL].fillna('').astype(str))

    scaler = StandardScaler(with_mean=False)
    X_train_text = scaler.fit_transform(X_train_text).astype(np.float32)
    X_val_text = scaler.transform(X_val_text).astype(np.float32)
    X_test_text = scaler.transform(X_test_text).astype(np.float32)

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]) if TORCHVISION_OK else None

    class FilteredMultimodalDataset(Dataset):
        def __init__(self, df, text_matrix, transform=None):
            self.df = df.reset_index(drop=True)
            self.text_matrix = text_matrix
            self.transform = transform
            self.image_col = 'image_path_primary' if 'image_path_primary' in self.df.columns else 'image_path'
        def __len__(self):
            return len(self.df)
        def __getitem__(self, idx):
            row = self.df.iloc[idx]
            label = int(row['label_id'])
            text_vec = self.text_matrix[idx]
            if sparse.issparse(text_vec):
                text_vec = text_vec.toarray().ravel()
            text_vec = torch.tensor(text_vec, dtype=torch.float32)
            path = str(row.get(self.image_col, ''))
            try:
                img = Image.open(path).convert('RGB')
                img = self.transform(img) if self.transform else torch.zeros(3, 224, 224)
            except Exception:
                img = torch.zeros(3, 224, 224)
            return text_vec, img, torch.tensor(label, dtype=torch.long)

    class SmallImageEncoder(nn.Module):
        def __init__(self, out_dim=128):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(), nn.AdaptiveAvgPool2d((1, 1)),
            )
            self.proj = nn.Sequential(nn.Flatten(), nn.Dropout(0.35), nn.Linear(128, out_dim), nn.ReLU())
        def forward(self, x):
            return self.proj(self.net(x))

    class ImageOnlyNet(nn.Module):
        def __init__(self, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.head = nn.Sequential(nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            return self.head(self.image(image))

    class ConcatFusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.head = nn.Sequential(nn.Linear(hidden * 2, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            return self.head(torch.cat([self.text(text), self.image(image)], dim=1))

    class ConsistencyFusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.head = nn.Sequential(nn.Linear(hidden * 4, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            t = self.text(text)
            i = self.image(image)
            return self.head(torch.cat([t, i, torch.abs(t - i), t * i], dim=1))

    class FrozenResNet50FusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            if not TORCHVISION_OK:
                raise RuntimeError('Torchvision unavailable.')
            weights = models.ResNet50_Weights.DEFAULT
            backbone = models.resnet50(weights=weights)
            feat_dim = backbone.fc.in_features
            backbone.fc = nn.Identity()
            for p in backbone.parameters():
                p.requires_grad = False
            self.backbone = backbone
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.image_proj = nn.Sequential(nn.Linear(feat_dim, hidden), nn.ReLU())
            self.head = nn.Sequential(nn.Linear(hidden * 4, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            with torch.no_grad():
                raw_i = self.backbone(image)
            t = self.text(text)
            i = self.image_proj(raw_i)
            return self.head(torch.cat([t, i, torch.abs(t - i), t * i], dim=1))

    def evaluate_torch_model(model, loader):
        model.eval()
        ys, preds, probs = [], [], []
        with torch.no_grad():
            for text, image, y in loader:
                text, image = text.to(DEVICE), image.to(DEVICE)
                logits = model(text, image)
                prob = torch.softmax(logits, dim=1)[:, 1].detach().cpu().numpy()
                pred = logits.argmax(dim=1).detach().cpu().numpy()
                ys.extend(y.numpy().tolist())
                preds.extend(pred.tolist())
                probs.extend(prob.tolist())
        return np.asarray(ys), np.asarray(preds), np.asarray(probs)

    def train_model(model, train_loader, val_loader, seed, model_name, lr=2e-4, weight_decay=1e-4):
        set_seed(seed)
        model = model.to(DEVICE)
        y_train_local = train_df['label_id'].astype(int).values
        counts = np.bincount(y_train_local, minlength=2)
        weights = torch.tensor(len(y_train_local) / (2 * np.maximum(counts, 1)), dtype=torch.float32, device=DEVICE)
        criterion = nn.CrossEntropyLoss(weight=weights)
        optimizer = optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=lr, weight_decay=weight_decay)
        best_state, best_f1, bad_epochs = None, -1, 0
        history = []
        for epoch in range(1, MAX_EPOCHS + 1):
            model.train()
            total_loss = 0.0
            for text, image, y in train_loader:
                text, image, y = text.to(DEVICE), image.to(DEVICE), y.to(DEVICE)
                optimizer.zero_grad()
                loss = criterion(model(text, image), y)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                total_loss += float(loss.item()) * len(y)
            yv, pv, qv = evaluate_torch_model(model, val_loader)
            val_f1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total_loss / len(train_loader.dataset), 'val_macro_f1': val_f1})
            if val_f1 > best_f1 + MIN_DELTA:
                best_f1 = val_f1
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                bad_epochs = 0
            else:
                bad_epochs += 1
            if bad_epochs >= PATIENCE:
                break
        if best_state is not None:
            model.load_state_dict(best_state)
        return model, pd.DataFrame(history)

    train_loader = DataLoader(FilteredMultimodalDataset(train_df, X_train_text, transform), batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
    val_loader = DataLoader(FilteredMultimodalDataset(val_df, X_val_text, transform), batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    test_loader = DataLoader(FilteredMultimodalDataset(test_df, X_test_text, transform), batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    model_specs = [
        ('Filtered GT6 Image-only CNN', lambda: ImageOnlyNet()),
        ('Filtered GT6 Concat fusion CNN+Text', lambda: ConcatFusionNet(X_train_text.shape[1])),
        ('Filtered GT6 Consistency fusion CNN+Text', lambda: ConsistencyFusionNet(X_train_text.shape[1])),
    ]
    if RUN_FROZEN_RESNET50:
        model_specs.append(('Filtered GT6 Frozen ResNet50 fusion CNN+Text', lambda: FrozenResNet50FusionNet(X_train_text.shape[1])))

    deep_rows = []
    for seed in RETRAIN_SEEDS:
        for name, ctor in model_specs:
            print(f'\\nTraining {name} seed={seed}')
            try:
                model, hist = train_model(ctor(), train_loader, val_loader, seed, name)
                y_true, y_pred, prob_fake = evaluate_torch_model(model, test_loader)
                run_name = f'{name} seed{seed}'
                deep_rows.append({'seed': seed, **compute_metrics(y_true, y_pred, prob_fake, run_name)})
                hist.to_csv(EXPERIMENT_DIR / f'{re.sub(r"[^A-Za-z0-9_.+-]+", "_", run_name)}_history.csv', index=False)
                pred_df, pred_path = save_prediction_file(test_df, y_pred, prob_fake, re.sub(r"[^A-Za-z0-9_.+-]+", "_", run_name))
                prediction_frames.append(pred_df.assign(model_name=run_name, model_family=name))
                torch.save(model.state_dict(), EXPERIMENT_DIR / f'{re.sub(r"[^A-Za-z0-9_.+-]+", "_", run_name)}.pt')
                display(pd.DataFrame([deep_rows[-1]]))
            except Exception as exc:
                print(f'Skipped {name} seed={seed}: {repr(exc)}')
                deep_rows.append({'seed': seed, 'model': f'{name} seed{seed}', 'status': 'skipped', 'reason': repr(exc)})

    deep_results = pd.DataFrame(deep_rows)
    deep_results.to_csv(EXPERIMENT_DIR / 'filtered_gt6_deep_retrain_metrics.csv', index=False)
    display(deep_results)

Device: cuda
\nTraining Filtered GT6 Image-only CNN seed=42

## 6. Optional BERT Text Retraining

In [ ]:
if RUN_TEXT_BERT:
    try:
        import torch
        from torch.utils.data import Dataset, DataLoader
        from transformers import AutoTokenizer, AutoModelForSequenceClassification
        import torch.nn as nn
        import torch.optim as optim

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        BERT_MODEL_NAME = 'bert-base-uncased'
        BERT_EPOCHS = 4
        BERT_BATCH_SIZE = 16
        BERT_LR = 2e-5

        tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL_NAME, local_files_only=True)

        class TextDataset(Dataset):
            def __init__(self, texts, labels):
                self.texts = list(texts)
                self.labels = np.asarray(labels, dtype=int)
            def __len__(self):
                return len(self.labels)
            def __getitem__(self, idx):
                enc = tokenizer(self.texts[idx], truncation=True, padding='max_length', max_length=128, return_tensors='pt')
                return {k: v.squeeze(0) for k, v in enc.items()}, torch.tensor(self.labels[idx], dtype=torch.long)

        def collate_text(batch):
            keys = batch[0][0].keys()
            enc = {k: torch.stack([b[0][k] for b in batch]) for k in keys}
            y = torch.stack([b[1] for b in batch])
            return enc, y

        train_loader = DataLoader(TextDataset(train_df[TEXT_COL].fillna('').astype(str), train_df['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=True, collate_fn=collate_text)
        val_loader = DataLoader(TextDataset(val_df[TEXT_COL].fillna('').astype(str), val_df['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=False, collate_fn=collate_text)
        test_loader = DataLoader(TextDataset(test_df[TEXT_COL].fillna('').astype(str), test_df['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=False, collate_fn=collate_text)

        model = AutoModelForSequenceClassification.from_pretrained(BERT_MODEL_NAME, num_labels=2, local_files_only=True).to(DEVICE)
        optimizer = optim.AdamW(model.parameters(), lr=BERT_LR, weight_decay=1e-4)
        best_state, best_f1 = None, -1
        bad = 0
        history = []

        def eval_bert(loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for enc, y in loader:
                    enc = {k: v.to(DEVICE) for k, v in enc.items()}
                    logits = model(**enc).logits
                    prob = torch.softmax(logits, dim=1)[:, 1].detach().cpu().numpy()
                    pred = logits.argmax(dim=1).detach().cpu().numpy()
                    ys.extend(y.numpy().tolist())
                    preds.extend(pred.tolist())
                    probs.extend(prob.tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        for epoch in range(1, BERT_EPOCHS + 1):
            model.train()
            total = 0.0
            for enc, y in train_loader:
                enc = {k: v.to(DEVICE) for k, v in enc.items()}
                y = y.to(DEVICE)
                optimizer.zero_grad()
                out = model(**enc, labels=y)
                out.loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                total += float(out.loss.item()) * len(y)
            yv, pv, qv = eval_bert(val_loader)
            vf1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total / len(train_df), 'val_macro_f1': vf1})
            print(f'BERT epoch {epoch}: val macro-F1={vf1:.4f}')
            if vf1 > best_f1 + MIN_DELTA:
                best_f1 = vf1
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                bad = 0
            else:
                bad += 1
            if bad >= PATIENCE:
                break

        if best_state is not None:
            model.load_state_dict(best_state)
        yt, pt, qt = eval_bert(test_loader)
        bert_metrics = pd.DataFrame([compute_metrics(yt, pt, qt, 'Filtered GT6 BERT text classifier')])
        bert_metrics.to_csv(EXPERIMENT_DIR / 'filtered_gt6_bert_text_metrics.csv', index=False)
        pd.DataFrame(history).to_csv(EXPERIMENT_DIR / 'filtered_gt6_bert_text_history.csv', index=False)
        pred_df, pred_path = save_prediction_file(test_df, pt, qt, 'filtered_gt6_bert_text')
        prediction_frames.append(pred_df.assign(model_name='filtered_gt6_bert_text', model_family='text_bert'))
        display(bert_metrics)
    except Exception as exc:
        print('BERT retraining skipped:', repr(exc))
        print('If needed, cache bert-base-uncased locally or set RUN_TEXT_BERT=False.')

## 7. Optional Rich Cached Feature MLP Retraining

In [ ]:
if RUN_RICH_CACHED_MLP:
    try:
        import torch
        import torch.nn as nn
        import torch.optim as optim
        from torch.utils.data import TensorDataset, DataLoader
        from sklearn.preprocessing import StandardScaler

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        def load_rich_filtered(split, keep_ids):
            meta = pd.read_csv(FINAL_ARTIFACT_DIR / f'rich_multimodal_{split}_ocr_blip_text.csv')
            z = np.load(FINAL_ARTIFACT_DIR / f'rich_multimodal_{split}_features.npz')
            mask = meta['id'].astype(str).isin(set(map(str, keep_ids))).values
            return meta.loc[mask].reset_index(drop=True), z['features'][mask].astype(np.float32), z['labels'][mask].astype(int)

        train_meta, Xtr, ytr = load_rich_filtered('train', train_df['id'])
        val_meta, Xva, yva = load_rich_filtered('val', val_df['id'])
        test_meta, Xte, yte = load_rich_filtered('test', test_df['id'])

        scaler = StandardScaler()
        Xtr = scaler.fit_transform(Xtr).astype(np.float32)
        Xva = scaler.transform(Xva).astype(np.float32)
        Xte = scaler.transform(Xte).astype(np.float32)

        class RichMLP(nn.Module):
            def __init__(self, dim):
                super().__init__()
                self.net = nn.Sequential(
                    nn.Linear(dim, 512), nn.ReLU(), nn.BatchNorm1d(512), nn.Dropout(0.45),
                    nn.Linear(512, 128), nn.ReLU(), nn.BatchNorm1d(128), nn.Dropout(0.35),
                    nn.Linear(128, 2),
                )
            def forward(self, x):
                return self.net(x)

        train_loader = DataLoader(TensorDataset(torch.tensor(Xtr), torch.tensor(ytr, dtype=torch.long)), batch_size=64, shuffle=True)
        val_loader = DataLoader(TensorDataset(torch.tensor(Xva), torch.tensor(yva, dtype=torch.long)), batch_size=128, shuffle=False)
        test_loader = DataLoader(TensorDataset(torch.tensor(Xte), torch.tensor(yte, dtype=torch.long)), batch_size=128, shuffle=False)

        model = RichMLP(Xtr.shape[1]).to(DEVICE)
        weights = torch.tensor(len(ytr) / (2 * np.maximum(np.bincount(ytr, minlength=2), 1)), dtype=torch.float32, device=DEVICE)
        criterion = nn.CrossEntropyLoss(weight=weights)
        optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
        best_state, best_f1, bad = None, -1, 0
        history = []

        def eval_mlp(loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for xb, yb in loader:
                    xb = xb.to(DEVICE)
                    logits = model(xb)
                    prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
                    pred = logits.argmax(dim=1).cpu().numpy()
                    ys.extend(yb.numpy().tolist())
                    preds.extend(pred.tolist())
                    probs.extend(prob.tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        for epoch in range(1, MAX_EPOCHS + 1):
            model.train()
            total = 0.0
            for xb, yb in train_loader:
                xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                optimizer.zero_grad()
                loss = criterion(model(xb), yb)
                loss.backward()
                optimizer.step()
                total += float(loss.item()) * len(yb)
            yv, pv, qv = eval_mlp(val_loader)
            vf1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total / len(ytr), 'val_macro_f1': vf1})
            if vf1 > best_f1 + MIN_DELTA:
                best_f1 = vf1
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                bad = 0
            else:
                bad += 1
            if bad >= PATIENCE:
                break

        if best_state is not None:
            model.load_state_dict(best_state)
        yt, pt, qt = eval_mlp(test_loader)
        rich_metrics = pd.DataFrame([compute_metrics(yt, pt, qt, 'Filtered GT6 OCR+BLIP+BERT+ResNet50 cached-feature MLP')])
        rich_metrics.to_csv(EXPERIMENT_DIR / 'filtered_gt6_rich_cached_mlp_metrics.csv', index=False)
        pd.DataFrame(history).to_csv(EXPERIMENT_DIR / 'filtered_gt6_rich_cached_mlp_history.csv', index=False)

        # test_meta order matches Xte/yte.
        test_meta2 = test_meta.copy()
        if 'label_id' not in test_meta2.columns:
            test_meta2['label_id'] = test_meta2['label'].map(LABEL_TO_ID)
        pred_df, pred_path = save_prediction_file(test_meta2, pt, qt, 'filtered_gt6_rich_cached_mlp')
        prediction_frames.append(pred_df.assign(model_name='filtered_gt6_rich_cached_mlp', model_family='rich_multimodal'))
        display(rich_metrics)
    except Exception as exc:
        print('Rich cached-feature MLP retraining skipped:', repr(exc))
        print('Run the rich branch once first if cached rich_multimodal_* feature files are missing.')

## 8. Voting Ensemble and Original-vs-Filtered Comparison

In [ ]:
all_metric_files = [
    EXPERIMENT_DIR / 'filtered_gt6_text_baseline_metrics.csv',
    EXPERIMENT_DIR / 'filtered_gt6_deep_retrain_metrics.csv',
    EXPERIMENT_DIR / 'filtered_gt6_bert_text_metrics.csv',
    EXPERIMENT_DIR / 'filtered_gt6_rich_cached_mlp_metrics.csv',
]

metric_frames = []
for path in all_metric_files:
    if path.exists():
        df = pd.read_csv(path)
        df['metric_file'] = path.name
        metric_frames.append(df)

filtered_metrics = pd.concat(metric_frames, ignore_index=True, sort=False) if metric_frames else pd.DataFrame()

if RUN_VOTING_ENSEMBLE and prediction_frames:
    votes = pd.concat(prediction_frames, ignore_index=True)
    vote_rows = []
    for sample_id, group in votes.groupby('id'):
        y = int(group['label_id'].iloc[0])
        fake_vote_rate = float(group['pred_id'].astype(int).mean())
        avg_prob = pd.to_numeric(group['prob_fake'], errors='coerce').mean()
        vote_rows.append({
            'id': sample_id,
            'label_id': y,
            'label': ID_TO_LABEL[y],
            'hard_vote_pred_id': int(fake_vote_rate >= 0.5),
            'soft_vote_pred_id': int(avg_prob >= 0.5),
            'fake_vote_rate': fake_vote_rate,
            'avg_prob_fake': avg_prob,
            'n_model_runs': int(group['model_name'].nunique()),
            'n_model_families': int(group['model_family'].nunique()),
        })
    vote_pred = pd.DataFrame(vote_rows)
    vote_metrics = pd.DataFrame([
        compute_metrics(vote_pred['label_id'], vote_pred['hard_vote_pred_id'], vote_pred['fake_vote_rate'], 'Filtered GT6 all-retrained hard vote'),
        compute_metrics(vote_pred['label_id'], vote_pred['soft_vote_pred_id'], vote_pred['avg_prob_fake'], 'Filtered GT6 all-retrained soft vote'),
    ])
    vote_pred.to_csv(EXPERIMENT_DIR / 'filtered_gt6_voting_predictions.csv', index=False)
    vote_metrics.to_csv(EXPERIMENT_DIR / 'filtered_gt6_voting_metrics.csv', index=False)
    filtered_metrics = pd.concat([filtered_metrics, vote_metrics.assign(metric_file='filtered_gt6_voting_metrics.csv')], ignore_index=True, sort=False)

if len(filtered_metrics):
    filtered_metrics.to_csv(EXPERIMENT_DIR / 'FILTERED_GT6_ALL_RETRAINED_METRICS.csv', index=False)
    display(filtered_metrics[['model', 'n_samples', 'accuracy', 'macro_f1', 'roc_auc', 'pr_auc', 'metric_file']].sort_values(['macro_f1', 'accuracy'], ascending=False))
else:
    print('No filtered metrics available yet. Run the training sections above.')

original_path = FINAL_ARTIFACT_DIR / 'report_table_classification_results.csv'
if original_path.exists() and len(filtered_metrics):
    original = pd.read_csv(original_path)
    original['experiment'] = 'original_main_test'
    filtered_show = filtered_metrics.copy()
    filtered_show['experiment'] = 'filtered_gt6_retrained'
    compare = pd.concat([
        original[['experiment', 'model', 'accuracy', 'macro_f1', 'roc_auc', 'pr_auc']] if set(['model','accuracy','macro_f1']).issubset(original.columns) else pd.DataFrame(),
        filtered_show[['experiment', 'model', 'accuracy', 'macro_f1', 'roc_auc', 'pr_auc']]
    ], ignore_index=True, sort=False)
    compare.to_csv(EXPERIMENT_DIR / 'original_vs_filtered_gt6_retrained_comparison.csv', index=False)
    display(compare)

print('Saved filtered experiment artifacts under:', EXPERIMENT_DIR)

---

## Original Source: `09_GT6_Clean_All_CrossValidation_Preparation.ipynb`

The following cells are preserved from the original notebook during GitHub reorganization.

# GT6 + Train-Hard Cleaned Normal-Split Retraining Notebook

This notebook is one complete experiment:

1. Load all final valid-image records.
2. Remove hard samples from the previous **test** analysis.
3. Also remove the **453 training samples** that were wrong in at least 6 saved model runs.
4. Create a new normal shuffled train/validation/test split.
5. Retrain the same model families used in the project.

Important: this is a diagnostic hard-sample removal experiment. Because the removed rows are selected using previous model errors, do not present this as the official unbiased benchmark. Use it as an analysis of noisy/hard examples.

## 1. Configuration

In [10]:
from pathlib import Path
import re
import json
import random
import warnings
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit

warnings.filterwarnings('ignore')
pd.set_option('display.max_colwidth', 140)
pd.set_option('display.max_columns', 80)

SEED = 42
TEST_SIZE = 0.10
VAL_SIZE_OF_REMAINING = 0.111  # approximately 10% validation and 80% train overall

DATA_SPLIT_DIR = Path('data_splits')
FINAL_ARTIFACT_DIR = Path('final_artifacts')
OUTPUT_SPLIT_DIR = DATA_SPLIT_DIR / 'normal_split_gt6_plus_trainhard_removed'
OUTPUT_ARTIFACT_DIR = Path('normal_split_gt6_plus_trainhard_artifacts')

for path in [OUTPUT_SPLIT_DIR, OUTPUT_ARTIFACT_DIR]:
    path.mkdir(parents=True, exist_ok=True)

LABEL_TO_ID = {'real': 0, 'fake': 1}
ID_TO_LABEL = {0: 'real', 1: 'fake'}

# Keep the previous test-hard rule from your GT6 experiment.
TEST_HARD_FILE = FINAL_ARTIFACT_DIR / 'final_multimodal_most_frequent_wrong_samples.csv'
TEST_HARD_COLUMN = 'wrong_multimodal_run_count'
TEST_HARD_RULE = '>'
TEST_HARD_THRESHOLD = 6

# Add the training-hard rule you requested.
TRAIN_HARD_FILE = FINAL_ARTIFACT_DIR / 'train_eval_most_frequent_wrong_samples.csv'
TRAIN_HARD_COLUMN = 'wrong_train_run_count'
TRAIN_HARD_RULE = '>='
TRAIN_HARD_THRESHOLD = 6

RUN_TFIDF = True
RUN_DEEP_MODELS = True
RUN_BERT = True
RUN_RICH_CACHED_MLP = True
RUN_VOTING = True

RETRAIN_SEEDS = [42, 123, 2026]
MAX_EPOCHS = 25
PATIENCE = 4
MIN_DELTA = 1e-4
BATCH_SIZE = 32
TEXT_MAX_FEATURES = 5000

print('Output split folder:', OUTPUT_SPLIT_DIR)
print('Output artifact folder:', OUTPUT_ARTIFACT_DIR)

Output split folder: data_splits\normal_split_gt6_plus_trainhard_removed
Output artifact folder: normal_split_gt6_plus_trainhard_artifacts

## 2. Load Final Valid-Image Data and Hard-Sample Lists

In [11]:
def load_final_valid_split(split):
    candidates = [
        DATA_SPLIT_DIR / f'{split}_valid_images_only_image_deleaked_with_content.csv',
        DATA_SPLIT_DIR / f'{split}_valid_images_only_image_deleaked.csv',
        DATA_SPLIT_DIR / f'{split}_valid_images_only.csv',
    ]
    for path in candidates:
        if path.exists():
            df = pd.read_csv(path)
            df['original_split'] = split
            return df, path
    raise FileNotFoundError(f'Missing final valid-image split for {split}. Checked: {candidates}')

def ids_by_rule(path, column, rule, threshold):
    if not Path(path).exists():
        print('Missing hard-sample file:', path)
        return set(), pd.DataFrame()
    df = pd.read_csv(path)
    if column not in df.columns:
        raise ValueError(f'{path} does not contain column {column}')
    mask = df[column].gt(threshold) if rule == '>' else df[column].ge(threshold)
    ids = set(df.loc[mask, 'id'].astype(str))
    return ids, df.loc[mask].copy()

loaded = []
load_rows = []
for split in ['train', 'val', 'test']:
    df, path = load_final_valid_split(split)
    loaded.append(df)
    load_rows.append({'split': split, 'file': str(path), 'rows': len(df)})

all_data_raw = pd.concat(loaded, ignore_index=True)

test_hard_ids, test_hard_rows = ids_by_rule(TEST_HARD_FILE, TEST_HARD_COLUMN, TEST_HARD_RULE, TEST_HARD_THRESHOLD)
train_hard_ids, train_hard_rows = ids_by_rule(TRAIN_HARD_FILE, TRAIN_HARD_COLUMN, TRAIN_HARD_RULE, TRAIN_HARD_THRESHOLD)
combined_hard_ids = test_hard_ids | train_hard_ids

display(pd.DataFrame(load_rows))
print(f'All loaded rows: {len(all_data_raw):,}')
print(f'Test-hard ids ({TEST_HARD_COLUMN} {TEST_HARD_RULE} {TEST_HARD_THRESHOLD}): {len(test_hard_ids):,}')
print(f'Train-hard ids ({TRAIN_HARD_COLUMN} {TRAIN_HARD_RULE} {TRAIN_HARD_THRESHOLD}): {len(train_hard_ids):,}')
print(f'Combined hard ids to remove: {len(combined_hard_ids):,}')

test_hard_rows.to_csv(OUTPUT_ARTIFACT_DIR / 'removed_source_test_hard_gt6.csv', index=False)
train_hard_rows.to_csv(OUTPUT_ARTIFACT_DIR / 'removed_source_train_hard_ge6.csv', index=False)

,split,file,rows
0,train,data_splits\train_valid_images_only_image_deleaked_with_content.csv,4829
1,val,data_splits\val_valid_images_only_image_deleaked_with_content.csv,541
2,test,data_splits\test_valid_images_only_image_deleaked_with_content.csv,518

All loaded rows: 5,888
Test-hard ids (wrong_multimodal_run_count > 6): 112
Train-hard ids (wrong_train_run_count >= 6): 453
Combined hard ids to remove: 565

## 3. Clean All Data, Remove Hard Samples, and Create Normal Shuffle Split

In [12]:
def clean_text(value):
    if pd.isna(value):
        return ''
    return re.sub(r'\s+', ' ', str(value)).strip()

def normalize_title(value):
    value = clean_text(value).lower()
    value = re.sub(r'[^a-z0-9]+', ' ', value)
    return re.sub(r'\s+', ' ', value).strip()

def path_exists(value):
    return isinstance(value, str) and bool(value.strip()) and Path(value).exists()

clean_all = all_data_raw.copy()

for col in ['id', 'news_url', 'title', 'source', 'label']:
    if col in clean_all.columns:
        clean_all[col] = clean_all[col].map(clean_text)

if 'label_id' not in clean_all.columns:
    clean_all['label_id'] = clean_all['label'].map(LABEL_TO_ID)
clean_all['label_id'] = clean_all['label_id'].astype(int)
clean_all['label'] = clean_all['label_id'].map(ID_TO_LABEL)

if 'text_for_model' not in clean_all.columns:
    if 'content' in clean_all.columns:
        content_available = clean_all['content'].fillna('').astype(str).str.len().ge(200)
        clean_all['text_for_model'] = np.where(content_available, clean_all['content'].fillna('').astype(str), clean_all['title'].fillna('').astype(str))
        clean_all['text_source_for_model'] = np.where(content_available, 'content', 'title')
    else:
        clean_all['text_for_model'] = clean_all['title'].fillna('').astype(str)
        clean_all['text_source_for_model'] = 'title'

clean_all['title_norm_split'] = clean_all['title'].map(normalize_title)

before_basic = len(clean_all)
clean_all = clean_all[clean_all['id'].ne('') & clean_all['title'].ne('')].copy()
clean_all = clean_all.drop_duplicates(subset=['id'], keep='first').copy()

image_col = 'image_path_primary' if 'image_path_primary' in clean_all.columns else 'image_path'
if image_col not in clean_all.columns:
    raise ValueError('No image path column found.')
clean_all['valid_image_path'] = clean_all[image_col].map(path_exists)

invalid_image_rows = clean_all[~clean_all['valid_image_path']].copy()
clean_all = clean_all[clean_all['valid_image_path']].copy()

hard_mask = clean_all['id'].astype(str).isin(combined_hard_ids)
removed_hard_rows = clean_all[hard_mask].copy()
clean_all_filtered = clean_all[~hard_mask].reset_index(drop=True).copy()

clean_all_filtered['split_stratum'] = clean_all_filtered['source'].astype(str) + '__' + clean_all_filtered['label'].astype(str)
clean_all_filtered['split_group'] = clean_all_filtered['title_norm_split'].where(
    clean_all_filtered['title_norm_split'].str.len() > 0,
    clean_all_filtered['id'].astype(str),
)

def grouped_shuffle_split(df, test_size, seed):
    splitter = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=seed)
    train_idx, test_idx = next(splitter.split(df, groups=df['split_group']))
    return df.iloc[train_idx].copy(), df.iloc[test_idx].copy()

train_val_df, test_df_new = grouped_shuffle_split(clean_all_filtered, TEST_SIZE, SEED)
train_df_new, val_df_new = grouped_shuffle_split(train_val_df, VAL_SIZE_OF_REMAINING, SEED)

train_df_new = train_df_new.sample(frac=1, random_state=SEED).reset_index(drop=True)
val_df_new = val_df_new.sample(frac=1, random_state=SEED).reset_index(drop=True)
test_df_new = test_df_new.sample(frac=1, random_state=SEED).reset_index(drop=True)

for name, df in [('train', train_df_new), ('val', val_df_new), ('test', test_df_new)]:
    df['split'] = name
    df.to_csv(OUTPUT_SPLIT_DIR / f'{name}.csv', index=False)

clean_all_filtered.to_csv(OUTPUT_SPLIT_DIR / 'clean_all_normal_split_hard_removed.csv', index=False)
removed_hard_rows.to_csv(OUTPUT_SPLIT_DIR / 'removed_combined_hard_samples.csv', index=False)
invalid_image_rows.to_csv(OUTPUT_SPLIT_DIR / 'invalid_image_rows_removed.csv', index=False)

split_leak_rows = []
split_frames = {'train': train_df_new, 'val': val_df_new, 'test': test_df_new}
for a, b in [('train', 'val'), ('train', 'test'), ('val', 'test')]:
    ids = set(split_frames[a]['id']) & set(split_frames[b]['id'])
    titles = (set(split_frames[a]['title_norm_split']) - {''}) & (set(split_frames[b]['title_norm_split']) - {''})
    split_leak_rows.append({'split_pair': f'{a}-{b}', 'id_overlap': len(ids), 'normalized_title_overlap': len(titles)})
split_leakage = pd.DataFrame(split_leak_rows)
if split_leakage[['id_overlap', 'normalized_title_overlap']].to_numpy().sum() > 0:
    raise ValueError('Leakage detected in normal split.')

audit = pd.DataFrame([
    {'stage': 'loaded_final_valid_image_splits', 'rows': len(all_data_raw)},
    {'stage': 'after_empty_id_title_and_duplicate_id_cleaning', 'rows': before_basic},
    {'stage': 'invalid_image_rows_removed', 'rows': len(invalid_image_rows)},
    {'stage': 'combined_hard_rows_removed_present_after_image_validation', 'rows': len(removed_hard_rows)},
    {'stage': 'clean_all_filtered', 'rows': len(clean_all_filtered)},
    {'stage': 'train', 'rows': len(train_df_new)},
    {'stage': 'val', 'rows': len(val_df_new)},
    {'stage': 'test', 'rows': len(test_df_new)},
])
audit.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_cleaning_audit.csv', index=False)
split_leakage.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_leakage_audit.csv', index=False)

display(audit)
display(split_leakage)
display(pd.concat([train_df_new, val_df_new, test_df_new]).groupby(['split', 'label']).size().unstack(fill_value=0))
display(pd.concat([train_df_new, val_df_new, test_df_new]).groupby(['split', 'source']).size().unstack(fill_value=0))

                                                       stage  rows
0                            loaded_final_valid_image_splits  5888
1             after_empty_id_title_and_duplicate_id_cleaning  5888
2                                 invalid_image_rows_removed   328
3  combined_hard_rows_removed_present_after_image_validation   519
4                                         clean_all_filtered  5041
5                                                      train  4035
6                                                        val   502
7                                                       test   504

   split_pair  id_overlap  normalized_title_overlap
0   train-val           0                         0
1  train-test           0                         0
2    val-test           0                         0

label  fake  real
split
test    243   261
train  1957  2078
val     236   266

source  gossipcop  politifact
split
test          491          13
train        3926         109
val           496           6

## 4. Shared Training Utilities

In [13]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_fscore_support, roc_auc_score, average_precision_score

def get_text_column(df):
    for col in ['text_for_model', 'content', 'title']:
        if col in df.columns:
            return col
    raise ValueError('No usable text column found.')

TEXT_COL = get_text_column(train_df_new)
print('Training text column:', TEXT_COL)

def metric_row(y_true, y_pred, prob_fake=None, model='model'):
    y_true = np.asarray(y_true, dtype=int)
    y_pred = np.asarray(y_pred, dtype=int)
    p, r, f1, support = precision_recall_fscore_support(y_true, y_pred, labels=[0, 1], zero_division=0)
    row = {
        'model': model,
        'n_samples': int(len(y_true)),
        'accuracy': accuracy_score(y_true, y_pred),
        'macro_f1': f1_score(y_true, y_pred, average='macro', zero_division=0),
        'real_precision': p[0],
        'real_recall': r[0],
        'real_f1': f1[0],
        'fake_precision': p[1],
        'fake_recall': r[1],
        'fake_f1': f1[1],
    }
    if prob_fake is not None and len(np.unique(y_true)) == 2:
        row['roc_auc'] = roc_auc_score(y_true, prob_fake)
        row['pr_auc'] = average_precision_score(y_true, prob_fake)
    else:
        row['roc_auc'] = np.nan
        row['pr_auc'] = np.nan
    return row

def safe_name(name):
    return re.sub(r'[^A-Za-z0-9_.+-]+', '_', str(name)).strip('_')

prediction_frames = []
metric_frames = []

def save_predictions(df, pred_id, prob_fake, model_name):
    out = df[['id', 'source', 'title', 'label', 'label_id', 'valid_image_path']].copy()
    if 'image_path_primary' in df.columns:
        out['image_path_primary'] = df['image_path_primary']
    out['model_name'] = model_name
    out['pred_id'] = np.asarray(pred_id, dtype=int)
    out['pred_label'] = [ID_TO_LABEL[int(x)] for x in pred_id]
    out['prob_fake'] = prob_fake
    out['correct'] = out['pred_id'].eq(out['label_id'].astype(int))
    path = OUTPUT_ARTIFACT_DIR / f'{safe_name(model_name)}_test_predictions.csv'
    out.to_csv(path, index=False)
    return out

Training text column: text_for_model

## 5. Text Baseline Retraining

In [14]:
if RUN_TFIDF:
    from sklearn.pipeline import Pipeline
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.dummy import DummyClassifier

    X_train = train_df_new[TEXT_COL].fillna('').astype(str)
    X_val = val_df_new[TEXT_COL].fillna('').astype(str)
    X_test = test_df_new[TEXT_COL].fillna('').astype(str)
    y_train = train_df_new['label_id'].astype(int).values
    y_test = test_df_new['label_id'].astype(int).values

    rows = []

    majority = DummyClassifier(strategy='most_frequent')
    majority.fit(X_train, y_train)
    pred = majority.predict(X_test)
    prob = np.full(len(y_test), float(np.mean(y_train == 1)))
    name = 'NormalSplit hard-removed Majority baseline'
    rows.append(metric_row(y_test, pred, prob, name))
    prediction_frames.append(save_predictions(test_df_new, pred, prob, name).assign(model_family='majority'))

    text_lr = Pipeline([
        ('tfidf', TfidfVectorizer(max_features=TEXT_MAX_FEATURES, ngram_range=(1, 2), min_df=2, sublinear_tf=True)),
        ('clf', LogisticRegression(max_iter=1500, class_weight='balanced', solver='liblinear', random_state=SEED)),
    ])
    text_lr.fit(X_train, y_train)
    pred = text_lr.predict(X_test)
    prob = text_lr.predict_proba(X_test)[:, 1]
    name = 'NormalSplit hard-removed TF-IDF Logistic Regression'
    rows.append(metric_row(y_test, pred, prob, name))
    prediction_frames.append(save_predictions(test_df_new, pred, prob, name).assign(model_family='text_tfidf'))

    text_metrics = pd.DataFrame(rows)
    text_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_text_baseline_metrics.csv', index=False)
    metric_frames.append(text_metrics)
    display(text_metrics)

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed Majority baseline,504,0.517857,0.341176,0.517857,1.000000,0.682353,0.000000,0.000000,0.000000,0.50000,0.482143
1,NormalSplit hard-removed TF-IDF Logistic Regression,504,0.825397,0.824399,0.807829,0.869732,0.837638,0.847534,0.777778,0.811159,0.89939,0.904405

## 6. Deep Multimodal Retraining

In [15]:
if RUN_DEEP_MODELS:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    from PIL import Image
    from scipy import sparse
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.preprocessing import StandardScaler
    try:
        from torchvision import transforms, models
        TORCHVISION_OK = True
    except Exception as exc:
        TORCHVISION_OK = False
        print('Torchvision unavailable; image models skipped:', repr(exc))

    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('Device:', DEVICE)

    def set_seed(seed):
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)

    vectorizer = TfidfVectorizer(max_features=TEXT_MAX_FEATURES, ngram_range=(1, 2), min_df=2, sublinear_tf=True)
    X_train_text = vectorizer.fit_transform(train_df_new[TEXT_COL].fillna('').astype(str))
    X_val_text = vectorizer.transform(val_df_new[TEXT_COL].fillna('').astype(str))
    X_test_text = vectorizer.transform(test_df_new[TEXT_COL].fillna('').astype(str))
    scaler = StandardScaler(with_mean=False)
    X_train_text = scaler.fit_transform(X_train_text).astype(np.float32)
    X_val_text = scaler.transform(X_val_text).astype(np.float32)
    X_test_text = scaler.transform(X_test_text).astype(np.float32)

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]) if TORCHVISION_OK else None

    class NewsDataset(Dataset):
        def __init__(self, df, text_matrix, transform=None):
            self.df = df.reset_index(drop=True)
            self.text_matrix = text_matrix
            self.transform = transform
            self.image_col = 'image_path_primary' if 'image_path_primary' in self.df.columns else 'image_path'
        def __len__(self):
            return len(self.df)
        def __getitem__(self, idx):
            row = self.df.iloc[idx]
            text_vec = self.text_matrix[idx]
            if sparse.issparse(text_vec):
                text_vec = text_vec.toarray().ravel()
            text_vec = torch.tensor(text_vec, dtype=torch.float32)
            path = str(row.get(self.image_col, ''))
            try:
                image = Image.open(path).convert('RGB')
                image = self.transform(image) if self.transform else torch.zeros(3, 224, 224)
            except Exception:
                image = torch.zeros(3, 224, 224)
            return text_vec, image, torch.tensor(int(row['label_id']), dtype=torch.long)

    class SmallImageEncoder(nn.Module):
        def __init__(self, out_dim=128):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(), nn.AdaptiveAvgPool2d((1, 1)),
            )
            self.proj = nn.Sequential(nn.Flatten(), nn.Linear(128, out_dim), nn.ReLU())
        def forward(self, x):
            return self.proj(self.net(x))

    class ImageOnlyNet(nn.Module):
        def __init__(self, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.head = nn.Sequential(nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            return self.head(self.image(image))

    class ConcatFusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.head = nn.Sequential(nn.Linear(hidden * 2, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            return self.head(torch.cat([self.text(text), self.image(image)], dim=1))

    class ConsistencyFusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            self.image = SmallImageEncoder(hidden)
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.head = nn.Sequential(nn.Linear(hidden * 4, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            t = self.text(text)
            i = self.image(image)
            return self.head(torch.cat([t, i, torch.abs(t - i), t * i], dim=1))

    class FrozenResNet50FusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            if not TORCHVISION_OK:
                raise RuntimeError('Torchvision unavailable.')
            weights = models.ResNet50_Weights.DEFAULT
            backbone = models.resnet50(weights=weights)
            feat_dim = backbone.fc.in_features
            backbone.fc = nn.Identity()
            for p in backbone.parameters():
                p.requires_grad = False
            self.backbone = backbone
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.image_proj = nn.Sequential(nn.Linear(feat_dim, hidden), nn.ReLU())
            self.head = nn.Sequential(nn.Linear(hidden * 4, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            with torch.no_grad():
                raw_i = self.backbone(image)
            t = self.text(text)
            i = self.image_proj(raw_i)
            return self.head(torch.cat([t, i, torch.abs(t - i), t * i], dim=1))

    class FrozenConvNeXtTinyFusionNet(nn.Module):
        def __init__(self, text_dim, hidden=128):
            super().__init__()
            if not TORCHVISION_OK:
                raise RuntimeError('Torchvision unavailable.')
            if not hasattr(models, 'convnext_tiny') or not hasattr(models, 'ConvNeXt_Tiny_Weights'):
                raise RuntimeError('This torchvision version does not provide ConvNeXt-Tiny.')
            weights = models.ConvNeXt_Tiny_Weights.DEFAULT
            backbone = models.convnext_tiny(weights=weights)
            feat_dim = backbone.classifier[2].in_features
            backbone.classifier[2] = nn.Identity()
            for p in backbone.parameters():
                p.requires_grad = False
            self.backbone = backbone
            self.text = nn.Sequential(nn.Linear(text_dim, hidden), nn.ReLU(), nn.Dropout(0.35))
            self.image_proj = nn.Sequential(nn.Linear(feat_dim, hidden), nn.ReLU())
            self.head = nn.Sequential(nn.Linear(hidden * 4, hidden), nn.ReLU(), nn.Dropout(0.45), nn.Linear(hidden, 2))
        def forward(self, text, image):
            with torch.no_grad():
                raw_i = self.backbone(image)
            t = self.text(text)
            i = self.image_proj(raw_i)
            return self.head(torch.cat([t, i, torch.abs(t - i), t * i], dim=1))

    def eval_model(model, loader):
        model.eval()
        ys, preds, probs = [], [], []
        with torch.no_grad():
            for text, image, y in loader:
                text, image = text.to(DEVICE), image.to(DEVICE)
                logits = model(text, image)
                prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
                pred = logits.argmax(dim=1).cpu().numpy()
                ys.extend(y.numpy().tolist())
                preds.extend(pred.tolist())
                probs.extend(prob.tolist())
        return np.asarray(ys), np.asarray(preds), np.asarray(probs)

    def train_model(model, train_loader, val_loader, y_train, lr=2e-4, weight_decay=1e-4):
        model = model.to(DEVICE)
        counts = np.bincount(np.asarray(y_train, dtype=int), minlength=2)
        weights = torch.tensor(len(y_train) / (2 * np.maximum(counts, 1)), dtype=torch.float32, device=DEVICE)
        criterion = nn.CrossEntropyLoss(weight=weights)
        optimizer = optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=lr, weight_decay=weight_decay)
        best_state, best_f1, bad = None, -1, 0
        history = []
        for epoch in range(1, MAX_EPOCHS + 1):
            model.train()
            total = 0.0
            for text, image, y in train_loader:
                text, image, y = text.to(DEVICE), image.to(DEVICE), y.to(DEVICE)
                optimizer.zero_grad()
                loss = criterion(model(text, image), y)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                total += float(loss.item()) * len(y)
            yv, pv, qv = eval_model(model, val_loader)
            vf1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total / len(train_loader.dataset), 'val_macro_f1': vf1})
            if vf1 > best_f1 + MIN_DELTA:
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                best_f1 = vf1
                bad = 0
            else:
                bad += 1
            if bad >= PATIENCE:
                break
        if best_state is not None:
            model.load_state_dict(best_state)
        return model, pd.DataFrame(history)

    train_loader = DataLoader(NewsDataset(train_df_new, X_train_text, transform), batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
    val_loader = DataLoader(NewsDataset(val_df_new, X_val_text, transform), batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    test_loader = DataLoader(NewsDataset(test_df_new, X_test_text, transform), batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    specs = [
        ('NormalSplit hard-removed Image-only CNN', lambda: ImageOnlyNet()),
        ('NormalSplit hard-removed Concat fusion CNN+Text', lambda: ConcatFusionNet(X_train_text.shape[1])),
        ('NormalSplit hard-removed Consistency fusion CNN+Text', lambda: ConsistencyFusionNet(X_train_text.shape[1])),
        ('NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text', lambda: FrozenResNet50FusionNet(X_train_text.shape[1])),
        ('NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text', lambda: FrozenConvNeXtTinyFusionNet(X_train_text.shape[1])),
    ]
    rows = []
    for seed in RETRAIN_SEEDS:
        set_seed(seed)
        for name, ctor in specs:
            print(f'Training {name} seed={seed}')
            try:
                model, hist = train_model(ctor(), train_loader, val_loader, train_df_new['label_id'].values)
                yt, pt, qt = eval_model(model, test_loader)
                run_name = f'{name} seed{seed}'
                rows.append({'seed': seed, **metric_row(yt, pt, qt, run_name)})
                hist.to_csv(OUTPUT_ARTIFACT_DIR / f'{safe_name(run_name)}_history.csv', index=False)
                prediction_frames.append(save_predictions(test_df_new, pt, qt, run_name).assign(model_family=name))
                torch.save(model.state_dict(), OUTPUT_ARTIFACT_DIR / f'{safe_name(run_name)}.pt')
                display(pd.DataFrame([rows[-1]]))
            except Exception as exc:
                print(f'Skipped {name} seed={seed}: {repr(exc)}')
                rows.append({'seed': seed, 'model': f'{name} seed{seed}', 'status': 'skipped', 'reason': repr(exc)})

    deep_metrics = pd.DataFrame(rows)
    deep_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_deep_model_metrics.csv', index=False)
    metric_frames.append(deep_metrics)
    display(deep_metrics)

Device: cuda
Training NormalSplit hard-removed Image-only CNN seed=42

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Image-only CNN seed42,504,0.559524,0.551839,0.563107,0.666667,0.610526,0.553846,0.444444,0.493151,0.605104,0.587445

Training NormalSplit hard-removed Concat fusion CNN+Text seed=42

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Concat fusion CNN+Text seed42,504,0.793651,0.793648,0.820408,0.770115,0.794466,0.76834,0.81893,0.792829,0.871119,0.874452

Training NormalSplit hard-removed Consistency fusion CNN+Text seed=42

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Consistency fusion CNN+Text seed42,504,0.781746,0.780748,0.772563,0.819923,0.795539,0.792952,0.740741,0.765957,0.869448,0.869854

Training NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed=42

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42,504,0.779762,0.77903,0.775735,0.808429,0.791745,0.784483,0.748971,0.766316,0.865002,0.869803

Training NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed=42
Downloading: "https://download.pytorch.org/models/convnext_tiny-983f1562.pth" to C:\Users\mosta/.cache\torch\hub\checkpoints\convnext_tiny-983f1562.pth

100%|██████████| 109M/109M [00:04<00:00, 25.0MB/s]

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42,504,0.78373,0.783422,0.790076,0.793103,0.791587,0.77686,0.773663,0.775258,0.87175,0.87573

Training NormalSplit hard-removed Image-only CNN seed=123

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,123,NormalSplit hard-removed Image-only CNN seed123,504,0.60119,0.600925,0.617188,0.605364,0.611219,0.584677,0.596708,0.590631,0.636969,0.604965

Training NormalSplit hard-removed Concat fusion CNN+Text seed=123

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,123,NormalSplit hard-removed Concat fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.83908,0.808118,0.811659,0.744856,0.776824,0.871324,0.875255

Training NormalSplit hard-removed Consistency fusion CNN+Text seed=123

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,123,NormalSplit hard-removed Consistency fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.83908,0.808118,0.811659,0.744856,0.776824,0.8659,0.86855

Training NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed=123

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,123,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123,504,0.799603,0.797993,0.777778,0.858238,0.816029,0.828704,0.736626,0.779956,0.874352,0.879085

Training NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed=123

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,123,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123,504,0.78373,0.783627,0.799213,0.777778,0.78835,0.768,0.790123,0.778905,0.878483,0.881921

Training NormalSplit hard-removed Image-only CNN seed=2026

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,2026,NormalSplit hard-removed Image-only CNN seed2026,504,0.563492,0.55221,0.563467,0.697318,0.623288,0.563536,0.419753,0.481132,0.612215,0.585191

Training NormalSplit hard-removed Concat fusion CNN+Text seed=2026

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,2026,NormalSplit hard-removed Concat fusion CNN+Text seed2026,504,0.801587,0.800882,0.794872,0.831418,0.812734,0.809524,0.769547,0.78903,0.885799,0.887811

Training NormalSplit hard-removed Consistency fusion CNN+Text seed=2026

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,2026,NormalSplit hard-removed Consistency fusion CNN+Text seed2026,504,0.791667,0.790876,0.784672,0.823755,0.803738,0.8,0.757202,0.778013,0.878877,0.880604

Training NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed=2026

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,2026,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026,504,0.789683,0.788212,0.77193,0.842912,0.805861,0.812785,0.73251,0.770563,0.876102,0.87522

Training NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed=2026

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,2026,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026,504,0.777778,0.775744,0.756014,0.842912,0.797101,0.807512,0.707819,0.754386,0.86959,0.878884

,seed,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,42,NormalSplit hard-removed Image-only CNN seed42,504,0.559524,0.551839,0.563107,0.666667,0.610526,0.553846,0.444444,0.493151,0.605104,0.587445
1,42,NormalSplit hard-removed Concat fusion CNN+Text seed42,504,0.793651,0.793648,0.820408,0.770115,0.794466,0.768340,0.818930,0.792829,0.871119,0.874452
2,42,NormalSplit hard-removed Consistency fusion CNN+Text seed42,504,0.781746,0.780748,0.772563,0.819923,0.795539,0.792952,0.740741,0.765957,0.869448,0.869854
3,42,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42,504,0.779762,0.779030,0.775735,0.808429,0.791745,0.784483,0.748971,0.766316,0.865002,0.869803
4,42,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42,504,0.783730,0.783422,0.790076,0.793103,0.791587,0.776860,0.773663,0.775258,0.871750,0.875730
5,123,NormalSplit hard-removed Image-only CNN seed123,504,0.601190,0.600925,0.617188,0.605364,0.611219,0.584677,0.596708,0.590631,0.636969,0.604965
6,123,NormalSplit hard-removed Concat fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.871324,0.875255
7,123,NormalSplit hard-removed Consistency fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.865900,0.868550
8,123,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123,504,0.799603,0.797993,0.777778,0.858238,0.816029,0.828704,0.736626,0.779956,0.874352,0.879085
9,123,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123,504,0.783730,0.783627,0.799213,0.777778,0.788350,0.768000,0.790123,0.778905,0.878483,0.881921
10,2026,NormalSplit hard-removed Image-only CNN seed2026,504,0.563492,0.552210,0.563467,0.697318,0.623288,0.563536,0.419753,0.481132,0.612215,0.585191
11,2026,NormalSplit hard-removed Concat fusion CNN+Text seed2026,504,0.801587,0.800882,0.794872,0.831418,0.812734,0.809524,0.769547,0.789030,0.885799,0.887811
12,2026,NormalSplit hard-removed Consistency fusion CNN+Text seed2026,504,0.791667,0.790876,0.784672,0.823755,0.803738,0.800000,0.757202,0.778013,0.878877,0.880604
13,2026,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026,504,0.789683,0.788212,0.771930,0.842912,0.805861,0.812785,0.732510,0.770563,0.876102,0.875220
14,2026,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026,504,0.777778,0.775744,0.756014,0.842912,0.797101,0.807512,0.707819,0.754386,0.869590,0.878884

## 7. BERT Text Classifier Retraining

In [16]:
if RUN_BERT:
    try:
        import torch
        from torch.utils.data import Dataset, DataLoader
        from transformers import AutoTokenizer, AutoModelForSequenceClassification
        import torch.optim as optim

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        BERT_MODEL_NAME = 'bert-base-uncased'
        BERT_BATCH_SIZE = 16
        BERT_EPOCHS = 4
        BERT_LR = 2e-5
        tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL_NAME, local_files_only=True)

        class TextDataset(Dataset):
            def __init__(self, texts, labels):
                self.texts = list(texts)
                self.labels = np.asarray(labels, dtype=int)
            def __len__(self):
                return len(self.labels)
            def __getitem__(self, idx):
                enc = tokenizer(self.texts[idx], truncation=True, padding='max_length', max_length=128, return_tensors='pt')
                return {k: v.squeeze(0) for k, v in enc.items()}, torch.tensor(self.labels[idx], dtype=torch.long)

        def collate(batch):
            keys = batch[0][0].keys()
            return {k: torch.stack([b[0][k] for b in batch]) for k in keys}, torch.stack([b[1] for b in batch])

        def eval_bert(model, loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for enc, y in loader:
                    enc = {k: v.to(DEVICE) for k, v in enc.items()}
                    logits = model(**enc).logits
                    prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
                    pred = logits.argmax(dim=1).cpu().numpy()
                    ys.extend(y.numpy().tolist())
                    preds.extend(pred.tolist())
                    probs.extend(prob.tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        train_loader = DataLoader(TextDataset(train_df_new[TEXT_COL].fillna('').astype(str), train_df_new['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=True, collate_fn=collate)
        val_loader = DataLoader(TextDataset(val_df_new[TEXT_COL].fillna('').astype(str), val_df_new['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=False, collate_fn=collate)
        test_loader = DataLoader(TextDataset(test_df_new[TEXT_COL].fillna('').astype(str), test_df_new['label_id']), batch_size=BERT_BATCH_SIZE, shuffle=False, collate_fn=collate)

        model = AutoModelForSequenceClassification.from_pretrained(BERT_MODEL_NAME, num_labels=2, local_files_only=True).to(DEVICE)
        optimizer = optim.AdamW(model.parameters(), lr=BERT_LR, weight_decay=1e-4)
        best_state, best_f1, bad = None, -1, 0
        history = []
        for epoch in range(1, BERT_EPOCHS + 1):
            model.train()
            total = 0.0
            for enc, y in train_loader:
                enc = {k: v.to(DEVICE) for k, v in enc.items()}
                y = y.to(DEVICE)
                optimizer.zero_grad()
                out = model(**enc, labels=y)
                out.loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                total += float(out.loss.item()) * len(y)
            yv, pv, qv = eval_bert(model, val_loader)
            vf1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total / len(train_df_new), 'val_macro_f1': vf1})
            print(f'BERT epoch={epoch} val macro-F1={vf1:.4f}')
            if vf1 > best_f1 + MIN_DELTA:
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                best_f1 = vf1
                bad = 0
            else:
                bad += 1
            if bad >= PATIENCE:
                break
        if best_state is not None:
            model.load_state_dict(best_state)
        yt, pt, qt = eval_bert(model, test_loader)
        name = 'NormalSplit hard-removed BERT text classifier'
        bert_metrics = pd.DataFrame([metric_row(yt, pt, qt, name)])
        bert_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_bert_text_metrics.csv', index=False)
        pd.DataFrame(history).to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_bert_text_history.csv', index=False)
        prediction_frames.append(save_predictions(test_df_new, pt, qt, name).assign(model_family='text_bert'))
        metric_frames.append(bert_metrics)
        display(bert_metrics)
    except Exception as exc:
        print('BERT retraining skipped:', repr(exc))
        print('Cache bert-base-uncased locally or set RUN_BERT=False.')

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17156.20it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

BERT epoch=1 val macro-F1=0.7779
BERT epoch=2 val macro-F1=0.8008
BERT epoch=3 val macro-F1=0.8166
BERT epoch=4 val macro-F1=0.8281

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed BERT text classifier,504,0.849206,0.848918,0.849057,0.862069,0.855513,0.849372,0.835391,0.842324,0.916418,0.919553

## 8. Rich Cached OCR+BLIP+BERT+ResNet50 MLP Retraining

In [17]:
if RUN_RICH_CACHED_MLP:
    try:
        import torch
        import torch.nn as nn
        import torch.optim as optim
        from torch.utils.data import TensorDataset, DataLoader
        from sklearn.preprocessing import StandardScaler

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        meta_parts, feat_parts, label_parts = [], [], []
        for split in ['train', 'val', 'test']:
            meta_path = FINAL_ARTIFACT_DIR / f'rich_multimodal_{split}_ocr_blip_text.csv'
            feat_path = FINAL_ARTIFACT_DIR / f'rich_multimodal_{split}_features.npz'
            if not meta_path.exists() or not feat_path.exists():
                raise FileNotFoundError(f'Missing rich cached features for {split}')
            meta = pd.read_csv(meta_path)
            z = np.load(feat_path)
            meta_parts.append(meta)
            feat_parts.append(z['features'].astype(np.float32))
            label_parts.append(z['labels'].astype(int))

        rich_meta = pd.concat(meta_parts, ignore_index=True)
        rich_X = np.vstack(feat_parts)
        rich_y = np.concatenate(label_parts)
        id_to_idx = {str(i): idx for idx, i in enumerate(rich_meta['id'].astype(str))}

        def arrays_for(df):
            ids = [str(i) for i in df['id']]
            keep = [i for i in ids if i in id_to_idx]
            filtered = df[df['id'].astype(str).isin(keep)].reset_index(drop=True)
            idx = [id_to_idx[str(i)] for i in filtered['id']]
            return filtered, rich_X[idx], rich_y[idx]

        train_rich_df, Xtr, ytr = arrays_for(train_df_new)
        val_rich_df, Xva, yva = arrays_for(val_df_new)
        test_rich_df, Xte, yte = arrays_for(test_df_new)

        scaler = StandardScaler()
        Xtr = scaler.fit_transform(Xtr).astype(np.float32)
        Xva = scaler.transform(Xva).astype(np.float32)
        Xte = scaler.transform(Xte).astype(np.float32)

        class RichMLP(nn.Module):
            def __init__(self, dim):
                super().__init__()
                self.net = nn.Sequential(
                    nn.Linear(dim, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.45),
                    nn.Linear(512, 128), nn.BatchNorm1d(128), nn.ReLU(), nn.Dropout(0.35),
                    nn.Linear(128, 2),
                )
            def forward(self, x):
                return self.net(x)

        train_loader = DataLoader(TensorDataset(torch.tensor(Xtr), torch.tensor(ytr, dtype=torch.long)), batch_size=64, shuffle=True)
        val_loader = DataLoader(TensorDataset(torch.tensor(Xva), torch.tensor(yva, dtype=torch.long)), batch_size=128, shuffle=False)
        test_loader = DataLoader(TensorDataset(torch.tensor(Xte), torch.tensor(yte, dtype=torch.long)), batch_size=128, shuffle=False)

        def eval_mlp(model, loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for xb, yb in loader:
                    xb = xb.to(DEVICE)
                    logits = model(xb)
                    prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
                    pred = logits.argmax(dim=1).cpu().numpy()
                    ys.extend(yb.numpy().tolist())
                    preds.extend(pred.tolist())
                    probs.extend(prob.tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        model = RichMLP(Xtr.shape[1]).to(DEVICE)
        weights = torch.tensor(len(ytr) / (2 * np.maximum(np.bincount(ytr, minlength=2), 1)), dtype=torch.float32, device=DEVICE)
        criterion = nn.CrossEntropyLoss(weight=weights)
        optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
        best_state, best_f1, bad = None, -1, 0
        history = []
        for epoch in range(1, MAX_EPOCHS + 1):
            model.train()
            total = 0.0
            for xb, yb in train_loader:
                xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                optimizer.zero_grad()
                loss = criterion(model(xb), yb)
                loss.backward()
                optimizer.step()
                total += float(loss.item()) * len(yb)
            yv, pv, qv = eval_mlp(model, val_loader)
            vf1 = f1_score(yv, pv, average='macro', zero_division=0)
            history.append({'epoch': epoch, 'train_loss': total / len(ytr), 'val_macro_f1': vf1})
            if vf1 > best_f1 + MIN_DELTA:
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                best_f1 = vf1
                bad = 0
            else:
                bad += 1
            if bad >= PATIENCE:
                break
        if best_state is not None:
            model.load_state_dict(best_state)
        yt, pt, qt = eval_mlp(model, test_loader)
        name = 'NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP'
        rich_metrics = pd.DataFrame([metric_row(yt, pt, qt, name)])
        rich_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_rich_cached_mlp_metrics.csv', index=False)
        pd.DataFrame(history).to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_rich_cached_mlp_history.csv', index=False)
        prediction_frames.append(save_predictions(test_rich_df, pt, qt, name).assign(model_family='rich_multimodal'))
        metric_frames.append(rich_metrics)
        display(rich_metrics)
    except Exception as exc:
        print('Rich cached MLP retraining skipped:', repr(exc))
        print('Run rich feature extraction first or set RUN_RICH_CACHED_MLP=False.')

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP,504,0.72619,0.724939,0.722022,0.766284,0.743494,0.731278,0.683128,0.706383,0.778424,0.748584

## 9. Voting Ensemble and Final Summary

In [18]:
all_metrics = []
for path in [
    OUTPUT_ARTIFACT_DIR / 'normal_split_text_baseline_metrics.csv',
    OUTPUT_ARTIFACT_DIR / 'normal_split_deep_model_metrics.csv',
    OUTPUT_ARTIFACT_DIR / 'normal_split_bert_text_metrics.csv',
    OUTPUT_ARTIFACT_DIR / 'normal_split_rich_cached_mlp_metrics.csv',
]:
    if path.exists():
        tmp = pd.read_csv(path)
        tmp['source_file'] = path.name
        all_metrics.append(tmp)

if RUN_VOTING:
    if not prediction_frames:
        for p in sorted(OUTPUT_ARTIFACT_DIR.glob('*_test_predictions.csv')):
            dfp = pd.read_csv(p)
            dfp['model_family'] = dfp.get('model_name', p.stem)
            prediction_frames.append(dfp)
    if prediction_frames:
        votes = pd.concat(prediction_frames, ignore_index=True)
        vote_rows = []
        for sample_id, group in votes.groupby('id'):
            y = int(group['label_id'].iloc[0])
            fake_vote_rate = float(group['pred_id'].astype(int).mean())
            avg_prob = pd.to_numeric(group['prob_fake'], errors='coerce').mean()
            vote_rows.append({
                'id': sample_id,
                'label_id': y,
                'label': ID_TO_LABEL[y],
                'hard_vote_pred_id': int(fake_vote_rate >= 0.5),
                'soft_vote_pred_id': int(avg_prob >= 0.5),
                'fake_vote_rate': fake_vote_rate,
                'avg_prob_fake': avg_prob,
                'n_model_runs': int(group['model_name'].nunique()),
                'n_model_families': int(group['model_family'].nunique()),
            })
        vote_pred = pd.DataFrame(vote_rows)
        vote_pred.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_voting_predictions.csv', index=False)
        vote_metrics = pd.DataFrame([
            metric_row(vote_pred['label_id'], vote_pred['hard_vote_pred_id'], vote_pred['fake_vote_rate'], 'NormalSplit hard-removed hard voting ensemble'),
            metric_row(vote_pred['label_id'], vote_pred['soft_vote_pred_id'], vote_pred['avg_prob_fake'], 'NormalSplit hard-removed soft voting ensemble'),
        ])
        vote_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_voting_metrics.csv', index=False)
        vote_metrics['source_file'] = 'normal_split_voting_metrics.csv'
        all_metrics.append(vote_metrics)

if all_metrics:
    final_metrics = pd.concat(all_metrics, ignore_index=True, sort=False)
    final_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'NORMAL_SPLIT_ALL_MODEL_METRICS_LONG.csv', index=False)
    summary = (
        final_metrics.dropna(subset=['macro_f1'])
        .groupby('model')[['accuracy', 'macro_f1', 'roc_auc', 'pr_auc']]
        .agg(['mean', 'std'])
        .sort_values(('macro_f1', 'mean'), ascending=False)
    )
    summary.to_csv(OUTPUT_ARTIFACT_DIR / 'NORMAL_SPLIT_ALL_MODEL_METRICS_SUMMARY.csv')
    display(final_metrics)
    display(summary)
else:
    print('No metrics yet. Run retraining cells above.')

print('Artifacts saved under:', OUTPUT_ARTIFACT_DIR)

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc,source_file,seed
0,NormalSplit hard-removed Majority baseline,504,0.517857,0.341176,0.517857,1.000000,0.682353,0.000000,0.000000,0.000000,0.500000,0.482143,normal_split_text_baseline_metrics.csv,NaN
1,NormalSplit hard-removed TF-IDF Logistic Regression,504,0.825397,0.824399,0.807829,0.869732,0.837638,0.847534,0.777778,0.811159,0.899390,0.904405,normal_split_text_baseline_metrics.csv,NaN
2,NormalSplit hard-removed Image-only CNN seed42,504,0.559524,0.551839,0.563107,0.666667,0.610526,0.553846,0.444444,0.493151,0.605104,0.587445,normal_split_deep_model_metrics.csv,42.0
3,NormalSplit hard-removed Concat fusion CNN+Text seed42,504,0.793651,0.793648,0.820408,0.770115,0.794466,0.768340,0.818930,0.792829,0.871119,0.874452,normal_split_deep_model_metrics.csv,42.0
4,NormalSplit hard-removed Consistency fusion CNN+Text seed42,504,0.781746,0.780748,0.772563,0.819923,0.795539,0.792952,0.740741,0.765957,0.869448,0.869854,normal_split_deep_model_metrics.csv,42.0
5,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42,504,0.779762,0.779030,0.775735,0.808429,0.791745,0.784483,0.748971,0.766316,0.865002,0.869803,normal_split_deep_model_metrics.csv,42.0
6,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42,504,0.783730,0.783422,0.790076,0.793103,0.791587,0.776860,0.773663,0.775258,0.871750,0.875730,normal_split_deep_model_metrics.csv,42.0
7,NormalSplit hard-removed Image-only CNN seed123,504,0.601190,0.600925,0.617188,0.605364,0.611219,0.584677,0.596708,0.590631,0.636969,0.604965,normal_split_deep_model_metrics.csv,123.0
8,NormalSplit hard-removed Concat fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.871324,0.875255,normal_split_deep_model_metrics.csv,123.0
9,NormalSplit hard-removed Consistency fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.865900,0.868550,normal_split_deep_model_metrics.csv,123.0
10,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123,504,0.799603,0.797993,0.777778,0.858238,0.816029,0.828704,0.736626,0.779956,0.874352,0.879085,normal_split_deep_model_metrics.csv,123.0
11,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123,504,0.783730,0.783627,0.799213,0.777778,0.788350,0.768000,0.790123,0.778905,0.878483,0.881921,normal_split_deep_model_metrics.csv,123.0
12,NormalSplit hard-removed Image-only CNN seed2026,504,0.563492,0.552210,0.563467,0.697318,0.623288,0.563536,0.419753,0.481132,0.612215,0.585191,normal_split_deep_model_metrics.csv,2026.0
13,NormalSplit hard-removed Concat fusion CNN+Text seed2026,504,0.801587,0.800882,0.794872,0.831418,0.812734,0.809524,0.769547,0.789030,0.885799,0.887811,normal_split_deep_model_metrics.csv,2026.0
14,NormalSplit hard-removed Consistency fusion CNN+Text seed2026,504,0.791667,0.790876,0.784672,0.823755,0.803738,0.800000,0.757202,0.778013,0.878877,0.880604,normal_split_deep_model_metrics.csv,2026.0
15,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026,504,0.789683,0.788212,0.771930,0.842912,0.805861,0.812785,0.732510,0.770563,0.876102,0.875220,normal_split_deep_model_metrics.csv,2026.0
16,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026,504,0.777778,0.775744,0.756014,0.842912,0.797101,0.807512,0.707819,0.754386,0.869590,0.878884,normal_split_deep_model_metrics.csv,2026.0
17,NormalSplit hard-removed BERT text classifier,504,0.849206,0.848918,0.849057,0.862069,0.855513,0.849372,0.835391,0.842324,0.916418,0.919553,normal_split_bert_text_metrics.csv,NaN
18,NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP,504,0.726190,0.724939,0.722022,0.766284,0.743494,0.731278,0.683128,0.706383,0.778424,0.748584,normal_split_rich_cached_mlp_metrics.csv,NaN
19,NormalSplit hard-removed hard voting ensemble,504,0.805556,0.804196,0.785965,0.858238,0.820513,0.831050,0.748971,0.787879,0.892350,0.875044,normal_split_voting_metrics.csv,NaN
20,NormalSplit hard-removed soft voting ensemble,504,0.809524,0.808435,0.793594,0.854406,0.822878,0.829596,0.761317,0.793991,0.906438,0.907945,normal_split_voting_metrics.csv,NaN

                                                                        accuracy  \
                                                                            mean
model
NormalSplit hard-removed BERT text classifier                           0.849206
NormalSplit hard-removed TF-IDF Logistic Regression                     0.825397
NormalSplit hard-removed soft voting ensemble                           0.809524
NormalSplit hard-removed hard voting ensemble                           0.805556
NormalSplit hard-removed Concat fusion CNN+Text seed2026                0.801587
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123        0.799603
NormalSplit hard-removed Concat fusion CNN+Text seed42                  0.793651
NormalSplit hard-removed Consistency fusion CNN+Text seed123            0.793651
NormalSplit hard-removed Concat fusion CNN+Text seed123                 0.793651
NormalSplit hard-removed Consistency fusion CNN+Text seed2026           0.791667
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026       0.789683
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123   0.783730
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42    0.783730
NormalSplit hard-removed Consistency fusion CNN+Text seed42             0.781746
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42         0.779762
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026  0.777778
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP      0.726190
NormalSplit hard-removed Image-only CNN seed123                         0.601190
NormalSplit hard-removed Image-only CNN seed2026                        0.563492
NormalSplit hard-removed Image-only CNN seed42                          0.559524
NormalSplit hard-removed Majority baseline                              0.517857

                                                                            \
                                                                       std
model
NormalSplit hard-removed BERT text classifier                          NaN
NormalSplit hard-removed TF-IDF Logistic Regression                    NaN
NormalSplit hard-removed soft voting ensemble                          NaN
NormalSplit hard-removed hard voting ensemble                          NaN
NormalSplit hard-removed Concat fusion CNN+Text seed2026               NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123       NaN
NormalSplit hard-removed Concat fusion CNN+Text seed42                 NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed123           NaN
NormalSplit hard-removed Concat fusion CNN+Text seed123                NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed2026          NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026      NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123  NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42   NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed42            NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42        NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026 NaN
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP     NaN
NormalSplit hard-removed Image-only CNN seed123                        NaN
NormalSplit hard-removed Image-only CNN seed2026                       NaN
NormalSplit hard-removed Image-only CNN seed42                         NaN
NormalSplit hard-removed Majority baseline                             NaN

                                                                        macro_f1  \
                                                                            mean
model
NormalSplit hard-removed BERT text classifier                           0.848918
NormalSplit hard-removed TF-IDF Logistic Regression                     0.824399
NormalSplit hard-removed soft voting ensemble                           0.808435
NormalSplit hard-removed hard voting ensemble                           0.804196
NormalSplit hard-removed Concat fusion CNN+Text seed2026                0.800882
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123        0.797993
NormalSplit hard-removed Concat fusion CNN+Text seed42                  0.793648
NormalSplit hard-removed Consistency fusion CNN+Text seed123            0.792471
NormalSplit hard-removed Concat fusion CNN+Text seed123                 0.792471
NormalSplit hard-removed Consistency fusion CNN+Text seed2026           0.790876
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026       0.788212
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123   0.783627
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42    0.783422
NormalSplit hard-removed Consistency fusion CNN+Text seed42             0.780748
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42         0.779030
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026  0.775744
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP      0.724939
NormalSplit hard-removed Image-only CNN seed123                         0.600925
NormalSplit hard-removed Image-only CNN seed2026                        0.552210
NormalSplit hard-removed Image-only CNN seed42                          0.551839
NormalSplit hard-removed Majority baseline                              0.341176

                                                                            \
                                                                       std
model
NormalSplit hard-removed BERT text classifier                          NaN
NormalSplit hard-removed TF-IDF Logistic Regression                    NaN
NormalSplit hard-removed soft voting ensemble                          NaN
NormalSplit hard-removed hard voting ensemble                          NaN
NormalSplit hard-removed Concat fusion CNN+Text seed2026               NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123       NaN
NormalSplit hard-removed Concat fusion CNN+Text seed42                 NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed123           NaN
NormalSplit hard-removed Concat fusion CNN+Text seed123                NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed2026          NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026      NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123  NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42   NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed42            NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42        NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026 NaN
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP     NaN
NormalSplit hard-removed Image-only CNN seed123                        NaN
NormalSplit hard-removed Image-only CNN seed2026                       NaN
NormalSplit hard-removed Image-only CNN seed42                         NaN
NormalSplit hard-removed Majority baseline                             NaN

                                                                         roc_auc  \
                                                                            mean
model
NormalSplit hard-removed BERT text classifier                           0.916418
NormalSplit hard-removed TF-IDF Logistic Regression                     0.899390
NormalSplit hard-removed soft voting ensemble                           0.906438
NormalSplit hard-removed hard voting ensemble                           0.892350
NormalSplit hard-removed Concat fusion CNN+Text seed2026                0.885799
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123        0.874352
NormalSplit hard-removed Concat fusion CNN+Text seed42                  0.871119
NormalSplit hard-removed Consistency fusion CNN+Text seed123            0.865900
NormalSplit hard-removed Concat fusion CNN+Text seed123                 0.871324
NormalSplit hard-removed Consistency fusion CNN+Text seed2026           0.878877
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026       0.876102
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123   0.878483
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42    0.871750
NormalSplit hard-removed Consistency fusion CNN+Text seed42             0.869448
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42         0.865002
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026  0.869590
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP      0.778424
NormalSplit hard-removed Image-only CNN seed123                         0.636969
NormalSplit hard-removed Image-only CNN seed2026                        0.612215
NormalSplit hard-removed Image-only CNN seed42                          0.605104
NormalSplit hard-removed Majority baseline                              0.500000

                                                                            \
                                                                       std
model
NormalSplit hard-removed BERT text classifier                          NaN
NormalSplit hard-removed TF-IDF Logistic Regression                    NaN
NormalSplit hard-removed soft voting ensemble                          NaN
NormalSplit hard-removed hard voting ensemble                          NaN
NormalSplit hard-removed Concat fusion CNN+Text seed2026               NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123       NaN
NormalSplit hard-removed Concat fusion CNN+Text seed42                 NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed123           NaN
NormalSplit hard-removed Concat fusion CNN+Text seed123                NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed2026          NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026      NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123  NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42   NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed42            NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42        NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026 NaN
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP     NaN
NormalSplit hard-removed Image-only CNN seed123                        NaN
NormalSplit hard-removed Image-only CNN seed2026                       NaN
NormalSplit hard-removed Image-only CNN seed42                         NaN
NormalSplit hard-removed Majority baseline                             NaN

                                                                          pr_auc  \
                                                                            mean
model
NormalSplit hard-removed BERT text classifier                           0.919553
NormalSplit hard-removed TF-IDF Logistic Regression                     0.904405
NormalSplit hard-removed soft voting ensemble                           0.907945
NormalSplit hard-removed hard voting ensemble                           0.875044
NormalSplit hard-removed Concat fusion CNN+Text seed2026                0.887811
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123        0.879085
NormalSplit hard-removed Concat fusion CNN+Text seed42                  0.874452
NormalSplit hard-removed Consistency fusion CNN+Text seed123            0.868550
NormalSplit hard-removed Concat fusion CNN+Text seed123                 0.875255
NormalSplit hard-removed Consistency fusion CNN+Text seed2026           0.880604
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026       0.875220
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123   0.881921
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42    0.875730
NormalSplit hard-removed Consistency fusion CNN+Text seed42             0.869854
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42         0.869803
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026  0.878884
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP      0.748584
NormalSplit hard-removed Image-only CNN seed123                         0.604965
NormalSplit hard-removed Image-only CNN seed2026                        0.585191
NormalSplit hard-removed Image-only CNN seed42                          0.587445
NormalSplit hard-removed Majority baseline                              0.482143


                                                                       std
model
NormalSplit hard-removed BERT text classifier                          NaN
NormalSplit hard-removed TF-IDF Logistic Regression                    NaN
NormalSplit hard-removed soft voting ensemble                          NaN
NormalSplit hard-removed hard voting ensemble                          NaN
NormalSplit hard-removed Concat fusion CNN+Text seed2026               NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123       NaN
NormalSplit hard-removed Concat fusion CNN+Text seed42                 NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed123           NaN
NormalSplit hard-removed Concat fusion CNN+Text seed123                NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed2026          NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026      NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123  NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42   NaN
NormalSplit hard-removed Consistency fusion CNN+Text seed42            NaN
NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42        NaN
NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026 NaN
NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP     NaN
NormalSplit hard-removed Image-only CNN seed123                        NaN
NormalSplit hard-removed Image-only CNN seed2026                       NaN
NormalSplit hard-removed Image-only CNN seed42                         NaN
NormalSplit hard-removed Majority baseline                             NaN

Artifacts saved under: normal_split_gt6_plus_trainhard_artifacts

## 10. Final Text Transformer Trials: DistilBERT and RoBERTa

In [19]:

# Final transformer trials.
# These are heavier text-only baselines; run after the split and shared utility cells.
RUN_DISTILBERT_ROBERTA = globals().get('RUN_DISTILBERT_ROBERTA', True)

if RUN_DISTILBERT_ROBERTA:
    try:
        import copy
        import torch
        from torch.utils.data import Dataset, DataLoader
        from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
        import torch.optim as optim

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print('Transformer trial device:', DEVICE)

        TRANSFORMER_TEXT_MODEL_SPECS = [
            ('DistilBERT', 'distilbert-base-uncased'),
            ('RoBERTa', 'roberta-base'),
        ]
        TRANSFORMER_LOCAL_FILES_ONLY = globals().get('TRANSFORMER_LOCAL_FILES_ONLY', False)
        TRANSFORMER_MAX_LENGTH = globals().get('TRANSFORMER_MAX_LENGTH', 256)
        TRANSFORMER_BATCH_SIZE = globals().get('TRANSFORMER_BATCH_SIZE', 16)
        TRANSFORMER_EPOCHS = globals().get('TRANSFORMER_EPOCHS', 4)
        TRANSFORMER_LR = globals().get('TRANSFORMER_LR', 2e-5)
        TRANSFORMER_WEIGHT_DECAY = globals().get('TRANSFORMER_WEIGHT_DECAY', 0.01)
        TRANSFORMER_PATIENCE = globals().get('TRANSFORMER_PATIENCE', 2)

        def set_text_transformer_seed(seed):
            random.seed(seed)
            np.random.seed(seed)
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)

        class TransformerTextDataset(Dataset):
            def __init__(self, texts, labels, tokenizer, max_length):
                self.labels = np.asarray(labels, dtype=int)
                self.encodings = tokenizer(
                    list(pd.Series(texts).fillna('').astype(str)),
                    truncation=True,
                    padding='max_length',
                    max_length=max_length,
                    return_tensors='pt',
                )
            def __len__(self):
                return len(self.labels)
            def __getitem__(self, idx):
                item = {k: v[idx] for k, v in self.encodings.items()}
                item['labels'] = torch.tensor(int(self.labels[idx]), dtype=torch.long)
                return item

        def evaluate_transformer_text_model(model, loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for batch in loader:
                    labels = batch.pop('labels').to(DEVICE)
                    batch = {k: v.to(DEVICE) for k, v in batch.items()}
                    logits = model(**batch).logits
                    prob = torch.softmax(logits, dim=1)[:, 1]
                    pred = logits.argmax(dim=1)
                    ys.extend(labels.cpu().numpy().tolist())
                    preds.extend(pred.cpu().numpy().tolist())
                    probs.extend(prob.cpu().numpy().tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        def train_transformer_text_model(model_name, pretrained_name, seed=SEED):
            set_text_transformer_seed(seed)
            tokenizer = AutoTokenizer.from_pretrained(
                pretrained_name,
                local_files_only=TRANSFORMER_LOCAL_FILES_ONLY,
            )
            model = AutoModelForSequenceClassification.from_pretrained(
                pretrained_name,
                num_labels=2,
                local_files_only=TRANSFORMER_LOCAL_FILES_ONLY,
            ).to(DEVICE)

            train_ds = TransformerTextDataset(
                train_df_new[TEXT_COL],
                train_df_new['label_id'].astype(int).values,
                tokenizer,
                TRANSFORMER_MAX_LENGTH,
            )
            val_ds = TransformerTextDataset(
                val_df_new[TEXT_COL],
                val_df_new['label_id'].astype(int).values,
                tokenizer,
                TRANSFORMER_MAX_LENGTH,
            )
            test_ds = TransformerTextDataset(
                test_df_new[TEXT_COL],
                test_df_new['label_id'].astype(int).values,
                tokenizer,
                TRANSFORMER_MAX_LENGTH,
            )
            train_loader = DataLoader(train_ds, batch_size=TRANSFORMER_BATCH_SIZE, shuffle=True)
            val_loader = DataLoader(val_ds, batch_size=TRANSFORMER_BATCH_SIZE, shuffle=False)
            test_loader = DataLoader(test_ds, batch_size=TRANSFORMER_BATCH_SIZE, shuffle=False)

            optimizer = optim.AdamW(model.parameters(), lr=TRANSFORMER_LR, weight_decay=TRANSFORMER_WEIGHT_DECAY)
            total_steps = max(1, len(train_loader) * TRANSFORMER_EPOCHS)
            scheduler = get_linear_schedule_with_warmup(
                optimizer,
                num_warmup_steps=max(1, int(0.1 * total_steps)),
                num_training_steps=total_steps,
            )

            best_state = None
            best_val_f1 = -1.0
            bad_epochs = 0
            history = []

            for epoch in range(1, TRANSFORMER_EPOCHS + 1):
                model.train()
                losses = []
                for batch in train_loader:
                    labels = batch.pop('labels').to(DEVICE)
                    batch = {k: v.to(DEVICE) for k, v in batch.items()}
                    optimizer.zero_grad(set_to_none=True)
                    loss = model(**batch, labels=labels).loss
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()
                    scheduler.step()
                    losses.append(float(loss.item()))

                yv, pv, qv = evaluate_transformer_text_model(model, val_loader)
                val_f1 = f1_score(yv, pv, average='macro', zero_division=0)
                row = {
                    'epoch': epoch,
                    'train_loss': float(np.mean(losses)) if losses else np.nan,
                    'val_macro_f1': float(val_f1),
                    'val_accuracy': float(accuracy_score(yv, pv)),
                    'val_roc_auc': float(roc_auc_score(yv, qv)) if len(np.unique(yv)) == 2 else np.nan,
                }
                history.append(row)
                print(f"{model_name} epoch {epoch}: loss={row['train_loss']:.4f}, val_macro_f1={val_f1:.4f}")

                if val_f1 > best_val_f1 + 1e-4:
                    best_val_f1 = val_f1
                    best_state = copy.deepcopy(model.state_dict())
                    bad_epochs = 0
                else:
                    bad_epochs += 1
                    if bad_epochs >= TRANSFORMER_PATIENCE:
                        print(f'{model_name}: early stopping at epoch {epoch}')
                        break

            if best_state is not None:
                model.load_state_dict(best_state)

            yt, pt, qt = evaluate_transformer_text_model(model, test_loader)
            run_name = f'NormalSplit hard-removed {model_name} text-only'
            metrics = metric_row(yt, pt, qt, run_name)
            hist = pd.DataFrame(history)
            hist.to_csv(OUTPUT_ARTIFACT_DIR / f'{safe_name(run_name)}_history.csv', index=False)
            torch.save(model.state_dict(), OUTPUT_ARTIFACT_DIR / f'{safe_name(run_name)}.pt')
            prediction_frames.append(
                save_predictions(test_df_new, pt, qt, run_name).assign(model_family=f'text_{model_name.lower()}')
            )

            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            return metrics

        transformer_rows = []
        for friendly_name, pretrained_name in TRANSFORMER_TEXT_MODEL_SPECS:
            print(f'Training {friendly_name} from {pretrained_name}')
            try:
                transformer_rows.append(train_transformer_text_model(friendly_name, pretrained_name))
                display(pd.DataFrame([transformer_rows[-1]]))
            except Exception as exc:
                print(f'Skipped {friendly_name}: {repr(exc)}')
                transformer_rows.append({
                    'model': f'NormalSplit hard-removed {friendly_name} text-only',
                    'status': 'skipped',
                    'reason': repr(exc),
                })

        transformer_text_metrics = pd.DataFrame(transformer_rows)
        transformer_text_metrics.to_csv(
            OUTPUT_ARTIFACT_DIR / 'normal_split_distilbert_roberta_text_metrics.csv',
            index=False,
        )
        metric_frames.append(transformer_text_metrics)

        metric_paths = [
            OUTPUT_ARTIFACT_DIR / 'normal_split_text_baseline_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_bert_text_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_distilbert_roberta_text_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_deep_model_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_rich_cached_mlp_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_voting_metrics.csv',
        ]
        available = []
        for path in metric_paths:
            if path.exists():
                tmp = pd.read_csv(path)
                tmp['source_file'] = path.name
                available.append(tmp)
        if available:
            final_with_transformers = pd.concat(available, ignore_index=True, sort=False)
            display(final_with_transformers.sort_values('macro_f1', ascending=False, na_position='last'))
        else:
            display(transformer_text_metrics)

    except Exception as exc:
        print('DistilBERT/RoBERTa final transformer section skipped.')
        print('Reason:', repr(exc))
        print('Install/cache transformers models, or set RUN_DISTILBERT_ROBERTA=False to skip this section.')
else:
    print('RUN_DISTILBERT_ROBERTA=False, skipping DistilBERT/RoBERTa final transformer trials.')

Transformer trial device: cuda
Training DistilBERT from distilbert-base-uncased

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 852.68it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DistilBERT epoch 1: loss=0.5462, val_macro_f1=0.7888
DistilBERT epoch 2: loss=0.3444, val_macro_f1=0.8306
DistilBERT epoch 3: loss=0.2170, val_macro_f1=0.8299
DistilBERT epoch 4: loss=0.1308, val_macro_f1=0.8278
DistilBERT: early stopping at epoch 4

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed DistilBERT text-only,504,0.81746,0.817319,0.828794,0.816092,0.822394,0.805668,0.81893,0.812245,0.908582,0.911938

Training RoBERTa from roberta-base

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 17320.21it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RoBERTa epoch 1: loss=0.5387, val_macro_f1=0.8197
RoBERTa epoch 2: loss=0.3523, val_macro_f1=0.8466
RoBERTa epoch 3: loss=0.2353, val_macro_f1=0.8415
RoBERTa epoch 4: loss=0.1439, val_macro_f1=0.8494

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed RoBERTa text-only,504,0.837302,0.836371,0.818505,0.881226,0.848708,0.860987,0.790123,0.824034,0.92807,0.925673

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc,source_file,seed
2,NormalSplit hard-removed BERT text classifier,504,0.849206,0.848918,0.849057,0.862069,0.855513,0.849372,0.835391,0.842324,0.916418,0.919553,normal_split_bert_text_metrics.csv,NaN
4,NormalSplit hard-removed RoBERTa text-only,504,0.837302,0.836371,0.818505,0.881226,0.848708,0.860987,0.790123,0.824034,0.928070,0.925673,normal_split_distilbert_roberta_text_metrics.csv,NaN
1,NormalSplit hard-removed TF-IDF Logistic Regression,504,0.825397,0.824399,0.807829,0.869732,0.837638,0.847534,0.777778,0.811159,0.899390,0.904405,normal_split_text_baseline_metrics.csv,NaN
3,NormalSplit hard-removed DistilBERT text-only,504,0.817460,0.817319,0.828794,0.816092,0.822394,0.805668,0.818930,0.812245,0.908582,0.911938,normal_split_distilbert_roberta_text_metrics.csv,NaN
22,NormalSplit hard-removed soft voting ensemble,504,0.809524,0.808435,0.793594,0.854406,0.822878,0.829596,0.761317,0.793991,0.906438,0.907945,normal_split_voting_metrics.csv,NaN
21,NormalSplit hard-removed hard voting ensemble,504,0.805556,0.804196,0.785965,0.858238,0.820513,0.831050,0.748971,0.787879,0.892350,0.875044,normal_split_voting_metrics.csv,NaN
16,NormalSplit hard-removed Concat fusion CNN+Text seed2026,504,0.801587,0.800882,0.794872,0.831418,0.812734,0.809524,0.769547,0.789030,0.885799,0.887811,normal_split_deep_model_metrics.csv,2026.0
13,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123,504,0.799603,0.797993,0.777778,0.858238,0.816029,0.828704,0.736626,0.779956,0.874352,0.879085,normal_split_deep_model_metrics.csv,123.0
6,NormalSplit hard-removed Concat fusion CNN+Text seed42,504,0.793651,0.793648,0.820408,0.770115,0.794466,0.768340,0.818930,0.792829,0.871119,0.874452,normal_split_deep_model_metrics.csv,42.0
12,NormalSplit hard-removed Consistency fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.865900,0.868550,normal_split_deep_model_metrics.csv,123.0
11,NormalSplit hard-removed Concat fusion CNN+Text seed123,504,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.871324,0.875255,normal_split_deep_model_metrics.csv,123.0
17,NormalSplit hard-removed Consistency fusion CNN+Text seed2026,504,0.791667,0.790876,0.784672,0.823755,0.803738,0.800000,0.757202,0.778013,0.878877,0.880604,normal_split_deep_model_metrics.csv,2026.0
18,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026,504,0.789683,0.788212,0.771930,0.842912,0.805861,0.812785,0.732510,0.770563,0.876102,0.875220,normal_split_deep_model_metrics.csv,2026.0
14,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123,504,0.783730,0.783627,0.799213,0.777778,0.788350,0.768000,0.790123,0.778905,0.878483,0.881921,normal_split_deep_model_metrics.csv,123.0
9,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42,504,0.783730,0.783422,0.790076,0.793103,0.791587,0.776860,0.773663,0.775258,0.871750,0.875730,normal_split_deep_model_metrics.csv,42.0
7,NormalSplit hard-removed Consistency fusion CNN+Text seed42,504,0.781746,0.780748,0.772563,0.819923,0.795539,0.792952,0.740741,0.765957,0.869448,0.869854,normal_split_deep_model_metrics.csv,42.0
8,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42,504,0.779762,0.779030,0.775735,0.808429,0.791745,0.784483,0.748971,0.766316,0.865002,0.869803,normal_split_deep_model_metrics.csv,42.0
19,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026,504,0.777778,0.775744,0.756014,0.842912,0.797101,0.807512,0.707819,0.754386,0.869590,0.878884,normal_split_deep_model_metrics.csv,2026.0
20,NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP,504,0.726190,0.724939,0.722022,0.766284,0.743494,0.731278,0.683128,0.706383,0.778424,0.748584,normal_split_rich_cached_mlp_metrics.csv,NaN
10,NormalSplit hard-removed Image-only CNN seed123,504,0.601190,0.600925,0.617188,0.605364,0.611219,0.584677,0.596708,0.590631,0.636969,0.604965,normal_split_deep_model_metrics.csv,123.0
15,NormalSplit hard-removed Image-only CNN seed2026,504,0.563492,0.552210,0.563467,0.697318,0.623288,0.563536,0.419753,0.481132,0.612215,0.585191,normal_split_deep_model_metrics.csv,2026.0
5,NormalSplit hard-removed Image-only CNN seed42,504,0.559524,0.551839,0.563107,0.666667,0.610526,0.553846,0.444444,0.493151,0.605104,0.587445,normal_split_deep_model_metrics.csv,42.0
0,NormalSplit hard-removed Majority baseline,504,0.517857,0.341176,0.517857,1.000000,0.682353,0.000000,0.000000,0.000000,0.500000,0.482143,normal_split_text_baseline_metrics.csv,NaN

## 11. Final Multimodal Vision-Encoder Trials: CLIP and Swin Transformer

In [20]:

# Final multimodal trials with stronger pretrained vision encoders.
# CLIP is image-text pretrained; Swin is a strong transformer image encoder.
RUN_CLIP_SWIN_TRIALS = globals().get('RUN_CLIP_SWIN_TRIALS', True)

if RUN_CLIP_SWIN_TRIALS:
    try:
        import copy
        import torch
        import torch.nn as nn
        import torch.optim as optim
        from torch.utils.data import TensorDataset, DataLoader
        from PIL import Image
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.preprocessing import StandardScaler

        DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print('CLIP/Swin trial device:', DEVICE)

        CLIP_LOCAL_FILES_ONLY = globals().get('CLIP_LOCAL_FILES_ONLY', False)
        CLIP_BATCH_SIZE = globals().get('CLIP_BATCH_SIZE', 16)
        CLIP_MODEL_SPECS = globals().get('CLIP_MODEL_SPECS', [
            ('CLIP ViT-B/32', 'openai/clip-vit-base-patch32'),
            # To run the larger option instead/as well, uncomment or override CLIP_MODEL_SPECS:
            # ('CLIP ViT-L/14', 'openai/clip-vit-large-patch14'),
        ])

        SWIN_BATCH_SIZE = globals().get('SWIN_BATCH_SIZE', 32)
        FEATURE_MLP_EPOCHS = globals().get('FEATURE_MLP_EPOCHS', 12)
        FEATURE_MLP_LR = globals().get('FEATURE_MLP_LR', 2e-4)
        FEATURE_MLP_WEIGHT_DECAY = globals().get('FEATURE_MLP_WEIGHT_DECAY', 1e-4)
        FEATURE_MLP_PATIENCE = globals().get('FEATURE_MLP_PATIENCE', 3)

        def set_feature_seed(seed):
            random.seed(seed)
            np.random.seed(seed)
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)

        def open_rgb_or_blank(path):
            try:
                return Image.open(str(path)).convert('RGB')
            except Exception:
                return Image.new('RGB', (224, 224), color=(0, 0, 0))

        def model_image_paths(df):
            image_col = 'image_path_primary' if 'image_path_primary' in df.columns else 'image_path'
            return df[image_col].fillna('').astype(str).tolist()

        class FeatureMLP(nn.Module):
            def __init__(self, in_dim, hidden=256, dropout=0.45):
                super().__init__()
                self.net = nn.Sequential(
                    nn.Linear(in_dim, hidden),
                    nn.ReLU(),
                    nn.BatchNorm1d(hidden),
                    nn.Dropout(dropout),
                    nn.Linear(hidden, hidden // 2),
                    nn.ReLU(),
                    nn.Dropout(dropout),
                    nn.Linear(hidden // 2, 2),
                )
            def forward(self, x):
                return self.net(x)

        def evaluate_feature_model(model, loader):
            model.eval()
            ys, preds, probs = [], [], []
            with torch.no_grad():
                for xb, yb in loader:
                    xb = xb.to(DEVICE)
                    logits = model(xb)
                    prob = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
                    pred = logits.argmax(dim=1).cpu().numpy()
                    ys.extend(yb.numpy().tolist())
                    preds.extend(pred.tolist())
                    probs.extend(prob.tolist())
            return np.asarray(ys), np.asarray(preds), np.asarray(probs)

        def train_feature_classifier(name, X_train, X_val, X_test, seed=SEED):
            set_feature_seed(seed)
            y_train = train_df_new['label_id'].astype(int).values
            y_val = val_df_new['label_id'].astype(int).values
            y_test = test_df_new['label_id'].astype(int).values

            X_train = np.asarray(X_train, dtype=np.float32)
            X_val = np.asarray(X_val, dtype=np.float32)
            X_test = np.asarray(X_test, dtype=np.float32)

            train_loader = DataLoader(
                TensorDataset(torch.tensor(X_train), torch.tensor(y_train, dtype=torch.long)),
                batch_size=64,
                shuffle=True,
            )
            val_loader = DataLoader(
                TensorDataset(torch.tensor(X_val), torch.tensor(y_val, dtype=torch.long)),
                batch_size=128,
                shuffle=False,
            )
            test_loader = DataLoader(
                TensorDataset(torch.tensor(X_test), torch.tensor(y_test, dtype=torch.long)),
                batch_size=128,
                shuffle=False,
            )

            model = FeatureMLP(X_train.shape[1]).to(DEVICE)
            counts = np.bincount(y_train, minlength=2)
            class_weights = torch.tensor(counts.sum() / np.maximum(counts, 1), dtype=torch.float32).to(DEVICE)
            criterion = nn.CrossEntropyLoss(weight=class_weights)
            optimizer = optim.AdamW(model.parameters(), lr=FEATURE_MLP_LR, weight_decay=FEATURE_MLP_WEIGHT_DECAY)

            best_state = None
            best_val_f1 = -1.0
            bad_epochs = 0
            history = []

            for epoch in range(1, FEATURE_MLP_EPOCHS + 1):
                model.train()
                losses = []
                for xb, yb in train_loader:
                    xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                    optimizer.zero_grad(set_to_none=True)
                    loss = criterion(model(xb), yb)
                    loss.backward()
                    optimizer.step()
                    losses.append(float(loss.item()))

                yv, pv, qv = evaluate_feature_model(model, val_loader)
                val_f1 = f1_score(yv, pv, average='macro', zero_division=0)
                row = {
                    'epoch': epoch,
                    'train_loss': float(np.mean(losses)) if losses else np.nan,
                    'val_macro_f1': float(val_f1),
                    'val_accuracy': float(accuracy_score(yv, pv)),
                    'val_roc_auc': float(roc_auc_score(yv, qv)) if len(np.unique(yv)) == 2 else np.nan,
                }
                history.append(row)
                print(f"{name} epoch {epoch}: loss={row['train_loss']:.4f}, val_macro_f1={val_f1:.4f}")

                if val_f1 > best_val_f1 + 1e-4:
                    best_val_f1 = val_f1
                    best_state = copy.deepcopy(model.state_dict())
                    bad_epochs = 0
                else:
                    bad_epochs += 1
                    if bad_epochs >= FEATURE_MLP_PATIENCE:
                        print(f'{name}: early stopping at epoch {epoch}')
                        break

            if best_state is not None:
                model.load_state_dict(best_state)

            yt, pt, qt = evaluate_feature_model(model, test_loader)
            metrics = metric_row(yt, pt, qt, name)
            pd.DataFrame(history).to_csv(OUTPUT_ARTIFACT_DIR / f'{safe_name(name)}_history.csv', index=False)
            torch.save(model.state_dict(), OUTPUT_ARTIFACT_DIR / f'{safe_name(name)}.pt')
            prediction_frames.append(save_predictions(test_df_new, pt, qt, name).assign(model_family=name))

            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            return metrics

        def extract_clip_features(model_name):
            from transformers import CLIPModel, CLIPProcessor

            processor = CLIPProcessor.from_pretrained(model_name, local_files_only=CLIP_LOCAL_FILES_ONLY)
            clip_model = CLIPModel.from_pretrained(model_name, local_files_only=CLIP_LOCAL_FILES_ONLY).to(DEVICE)
            clip_model.eval()

            def pooled_output_to_tensor(output):
                if isinstance(output, torch.Tensor):
                    return output
                if hasattr(output, 'pooler_output') and output.pooler_output is not None:
                    return output.pooler_output
                if hasattr(output, 'last_hidden_state') and output.last_hidden_state is not None:
                    return output.last_hidden_state[:, 0]
                if isinstance(output, (tuple, list)):
                    if len(output) > 1 and output[1] is not None:
                        return output[1]
                    if len(output) > 0 and isinstance(output[0], torch.Tensor) and output[0].ndim == 3:
                        return output[0][:, 0]
                    if len(output) > 0 and isinstance(output[0], torch.Tensor):
                        return output[0]
                raise TypeError(f'Cannot convert CLIP output type {type(output)} to tensor.')

            def maybe_project(features, projection):
                if projection is None:
                    return features
                in_features = getattr(projection, 'in_features', None)
                if in_features is not None and features.shape[-1] == in_features:
                    return projection(features)
                return features

            def get_projected_clip_features(inputs):
                try:
                    raw_image = clip_model.get_image_features(pixel_values=inputs['pixel_values'])
                    image_features = pooled_output_to_tensor(raw_image)
                    image_features = maybe_project(image_features, getattr(clip_model, 'visual_projection', None))
                except Exception:
                    raw_image = clip_model.vision_model(pixel_values=inputs['pixel_values'])
                    image_features = pooled_output_to_tensor(raw_image)
                    image_features = maybe_project(image_features, getattr(clip_model, 'visual_projection', None))

                text_kwargs = {
                    'input_ids': inputs['input_ids'],
                    'attention_mask': inputs.get('attention_mask'),
                }
                text_kwargs = {k: v for k, v in text_kwargs.items() if v is not None}
                try:
                    raw_text = clip_model.get_text_features(**text_kwargs)
                    text_features = pooled_output_to_tensor(raw_text)
                    text_features = maybe_project(text_features, getattr(clip_model, 'text_projection', None))
                except Exception:
                    raw_text = clip_model.text_model(**text_kwargs)
                    text_features = pooled_output_to_tensor(raw_text)
                    text_features = maybe_project(text_features, getattr(clip_model, 'text_projection', None))

                if image_features.shape[-1] != text_features.shape[-1]:
                    raise ValueError(
                        f'CLIP image/text dimensions do not match after projection: '
                        f'{image_features.shape[-1]} vs {text_features.shape[-1]}'
                    )
                return image_features, text_features

            def encode_df(df):
                texts = df[TEXT_COL].fillna('').astype(str).tolist()
                paths = model_image_paths(df)
                feature_chunks = []
                with torch.no_grad():
                    for start in range(0, len(df), CLIP_BATCH_SIZE):
                        batch_texts = texts[start:start + CLIP_BATCH_SIZE]
                        batch_images = [open_rgb_or_blank(p) for p in paths[start:start + CLIP_BATCH_SIZE]]
                        inputs = processor(
                            text=batch_texts,
                            images=batch_images,
                            return_tensors='pt',
                            padding=True,
                            truncation=True,
                        )
                        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
                        image_features, text_features = get_projected_clip_features(inputs)
                        image_features = image_features / image_features.norm(dim=1, keepdim=True).clamp_min(1e-8)
                        text_features = text_features / text_features.norm(dim=1, keepdim=True).clamp_min(1e-8)
                        cosine = (image_features * text_features).sum(dim=1, keepdim=True)
                        fused = torch.cat([
                            text_features,
                            image_features,
                            torch.abs(text_features - image_features),
                            text_features * image_features,
                            cosine,
                        ], dim=1)
                        feature_chunks.append(fused.cpu().numpy())
                return np.vstack(feature_chunks).astype(np.float32)

            X_train_clip = encode_df(train_df_new)
            X_val_clip = encode_df(val_df_new)
            X_test_clip = encode_df(test_df_new)

            del clip_model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            return X_train_clip, X_val_clip, X_test_clip

        def extract_swin_fusion_features():
            try:
                from torchvision import models
            except Exception as exc:
                raise RuntimeError(f'Torchvision unavailable for Swin: {exc!r}')

            if not hasattr(models, 'swin_t') or not hasattr(models, 'Swin_T_Weights'):
                raise RuntimeError('This torchvision version does not provide Swin-T.')

            weights = models.Swin_T_Weights.DEFAULT
            transform = weights.transforms()
            swin = models.swin_t(weights=weights).to(DEVICE)
            swin.head = nn.Identity()
            for p in swin.parameters():
                p.requires_grad = False
            swin.eval()

            def encode_images(df):
                paths = model_image_paths(df)
                chunks = []
                with torch.no_grad():
                    for start in range(0, len(paths), SWIN_BATCH_SIZE):
                        images = [transform(open_rgb_or_blank(p)) for p in paths[start:start + SWIN_BATCH_SIZE]]
                        xb = torch.stack(images).to(DEVICE)
                        feats = swin(xb)
                        chunks.append(feats.cpu().numpy())
                return np.vstack(chunks).astype(np.float32)

            train_img = encode_images(train_df_new)
            val_img = encode_images(val_df_new)
            test_img = encode_images(test_df_new)

            vectorizer = TfidfVectorizer(max_features=TEXT_MAX_FEATURES, ngram_range=(1, 2), min_df=2, sublinear_tf=True)
            X_train_text = vectorizer.fit_transform(train_df_new[TEXT_COL].fillna('').astype(str))
            X_val_text = vectorizer.transform(val_df_new[TEXT_COL].fillna('').astype(str))
            X_test_text = vectorizer.transform(test_df_new[TEXT_COL].fillna('').astype(str))
            scaler = StandardScaler(with_mean=False)
            X_train_text = scaler.fit_transform(X_train_text).astype(np.float32).toarray()
            X_val_text = scaler.transform(X_val_text).astype(np.float32).toarray()
            X_test_text = scaler.transform(X_test_text).astype(np.float32).toarray()

            X_train = np.hstack([X_train_text, train_img]).astype(np.float32)
            X_val = np.hstack([X_val_text, val_img]).astype(np.float32)
            X_test = np.hstack([X_test_text, test_img]).astype(np.float32)

            del swin
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            return X_train, X_val, X_test

        clip_swin_rows = []

        for friendly_name, pretrained_name in CLIP_MODEL_SPECS:
            run_name = f'NormalSplit hard-removed {friendly_name} frozen multimodal fusion'
            print(f'Extracting/training {run_name} from {pretrained_name}')
            try:
                Xtr, Xva, Xte = extract_clip_features(pretrained_name)
                clip_swin_rows.append(train_feature_classifier(run_name, Xtr, Xva, Xte))
                display(pd.DataFrame([clip_swin_rows[-1]]))
            except Exception as exc:
                print(f'Skipped {run_name}: {repr(exc)}')
                clip_swin_rows.append({'model': run_name, 'status': 'skipped', 'reason': repr(exc)})

        swin_name = 'NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion'
        print(f'Extracting/training {swin_name}')
        try:
            Xtr, Xva, Xte = extract_swin_fusion_features()
            clip_swin_rows.append(train_feature_classifier(swin_name, Xtr, Xva, Xte))
            display(pd.DataFrame([clip_swin_rows[-1]]))
        except Exception as exc:
            print(f'Skipped {swin_name}: {repr(exc)}')
            clip_swin_rows.append({'model': swin_name, 'status': 'skipped', 'reason': repr(exc)})

        clip_swin_metrics = pd.DataFrame(clip_swin_rows)
        clip_swin_metrics.to_csv(OUTPUT_ARTIFACT_DIR / 'normal_split_clip_swin_metrics.csv', index=False)
        metric_frames.append(clip_swin_metrics)

        metric_paths = [
            OUTPUT_ARTIFACT_DIR / 'normal_split_text_baseline_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_bert_text_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_distilbert_roberta_text_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_deep_model_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_rich_cached_mlp_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_clip_swin_metrics.csv',
            OUTPUT_ARTIFACT_DIR / 'normal_split_voting_metrics.csv',
        ]
        available = []
        for path in metric_paths:
            if path.exists():
                tmp = pd.read_csv(path)
                tmp['source_file'] = path.name
                available.append(tmp)
        if available:
            final_with_clip_swin = pd.concat(available, ignore_index=True, sort=False)
            display(final_with_clip_swin.sort_values('macro_f1', ascending=False, na_position='last'))
        else:
            display(clip_swin_metrics)

    except Exception as exc:
        print('CLIP/Swin final multimodal section skipped.')
        print('Reason:', repr(exc))
        print('Install/cache transformers and torchvision models, or set RUN_CLIP_SWIN_TRIALS=False to skip this section.')
else:
    print('RUN_CLIP_SWIN_TRIALS=False, skipping CLIP/Swin final multimodal trials.')

CLIP/Swin trial device: cuda
Extracting/training NormalSplit hard-removed CLIP ViT-B/32 frozen multimodal fusion from openai/clip-vit-base-patch32

Loading weights: 100%|██████████| 398/398 [00:00<00:00, 46726.00it/s]

Skipped NormalSplit hard-removed CLIP ViT-B/32 frozen multimodal fusion: AttributeError("'BaseModelOutputWithPooling' object has no attribute 'norm'")
Extracting/training NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion
Downloading: "https://download.pytorch.org/models/swin_t-704ceda3.pth" to C:\Users\mosta/.cache\torch\hub\checkpoints\swin_t-704ceda3.pth

100%|██████████| 108M/108M [00:05<00:00, 22.1MB/s]

NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 1: loss=0.6026, val_macro_f1=0.7951
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 2: loss=0.3742, val_macro_f1=0.7970
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 3: loss=0.2245, val_macro_f1=0.8107
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 4: loss=0.1217, val_macro_f1=0.7904
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 5: loss=0.0641, val_macro_f1=0.7860
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion epoch 6: loss=0.0353, val_macro_f1=0.7866
NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion: early stopping at epoch 6

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc
0,NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion,504,0.809524,0.80778,0.783505,0.873563,0.826087,0.84507,0.740741,0.789474,0.897372,0.899746

,model,n_samples,accuracy,macro_f1,real_precision,real_recall,real_f1,fake_precision,fake_recall,fake_f1,roc_auc,pr_auc,source_file,seed,status,reason
2,NormalSplit hard-removed BERT text classifier,504.0,0.849206,0.848918,0.849057,0.862069,0.855513,0.849372,0.835391,0.842324,0.916418,0.919553,normal_split_bert_text_metrics.csv,NaN,NaN,NaN
4,NormalSplit hard-removed RoBERTa text-only,504.0,0.837302,0.836371,0.818505,0.881226,0.848708,0.860987,0.790123,0.824034,0.928070,0.925673,normal_split_distilbert_roberta_text_metrics.csv,NaN,NaN,NaN
1,NormalSplit hard-removed TF-IDF Logistic Regression,504.0,0.825397,0.824399,0.807829,0.869732,0.837638,0.847534,0.777778,0.811159,0.899390,0.904405,normal_split_text_baseline_metrics.csv,NaN,NaN,NaN
3,NormalSplit hard-removed DistilBERT text-only,504.0,0.817460,0.817319,0.828794,0.816092,0.822394,0.805668,0.818930,0.812245,0.908582,0.911938,normal_split_distilbert_roberta_text_metrics.csv,NaN,NaN,NaN
24,NormalSplit hard-removed soft voting ensemble,504.0,0.809524,0.808435,0.793594,0.854406,0.822878,0.829596,0.761317,0.793991,0.906438,0.907945,normal_split_voting_metrics.csv,NaN,NaN,NaN
22,NormalSplit hard-removed Swin-T frozen image + TF-IDF fusion,504.0,0.809524,0.807780,0.783505,0.873563,0.826087,0.845070,0.740741,0.789474,0.897372,0.899746,normal_split_clip_swin_metrics.csv,NaN,NaN,NaN
23,NormalSplit hard-removed hard voting ensemble,504.0,0.805556,0.804196,0.785965,0.858238,0.820513,0.831050,0.748971,0.787879,0.892350,0.875044,normal_split_voting_metrics.csv,NaN,NaN,NaN
16,NormalSplit hard-removed Concat fusion CNN+Text seed2026,504.0,0.801587,0.800882,0.794872,0.831418,0.812734,0.809524,0.769547,0.789030,0.885799,0.887811,normal_split_deep_model_metrics.csv,2026.0,NaN,NaN
13,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed123,504.0,0.799603,0.797993,0.777778,0.858238,0.816029,0.828704,0.736626,0.779956,0.874352,0.879085,normal_split_deep_model_metrics.csv,123.0,NaN,NaN
6,NormalSplit hard-removed Concat fusion CNN+Text seed42,504.0,0.793651,0.793648,0.820408,0.770115,0.794466,0.768340,0.818930,0.792829,0.871119,0.874452,normal_split_deep_model_metrics.csv,42.0,NaN,NaN
12,NormalSplit hard-removed Consistency fusion CNN+Text seed123,504.0,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.865900,0.868550,normal_split_deep_model_metrics.csv,123.0,NaN,NaN
11,NormalSplit hard-removed Concat fusion CNN+Text seed123,504.0,0.793651,0.792471,0.779359,0.839080,0.808118,0.811659,0.744856,0.776824,0.871324,0.875255,normal_split_deep_model_metrics.csv,123.0,NaN,NaN
17,NormalSplit hard-removed Consistency fusion CNN+Text seed2026,504.0,0.791667,0.790876,0.784672,0.823755,0.803738,0.800000,0.757202,0.778013,0.878877,0.880604,normal_split_deep_model_metrics.csv,2026.0,NaN,NaN
18,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed2026,504.0,0.789683,0.788212,0.771930,0.842912,0.805861,0.812785,0.732510,0.770563,0.876102,0.875220,normal_split_deep_model_metrics.csv,2026.0,NaN,NaN
14,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed123,504.0,0.783730,0.783627,0.799213,0.777778,0.788350,0.768000,0.790123,0.778905,0.878483,0.881921,normal_split_deep_model_metrics.csv,123.0,NaN,NaN
9,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed42,504.0,0.783730,0.783422,0.790076,0.793103,0.791587,0.776860,0.773663,0.775258,0.871750,0.875730,normal_split_deep_model_metrics.csv,42.0,NaN,NaN
7,NormalSplit hard-removed Consistency fusion CNN+Text seed42,504.0,0.781746,0.780748,0.772563,0.819923,0.795539,0.792952,0.740741,0.765957,0.869448,0.869854,normal_split_deep_model_metrics.csv,42.0,NaN,NaN
8,NormalSplit hard-removed Frozen ResNet50 fusion CNN+Text seed42,504.0,0.779762,0.779030,0.775735,0.808429,0.791745,0.784483,0.748971,0.766316,0.865002,0.869803,normal_split_deep_model_metrics.csv,42.0,NaN,NaN
19,NormalSplit hard-removed Frozen ConvNeXt-Tiny fusion CNN+Text seed2026,504.0,0.777778,0.775744,0.756014,0.842912,0.797101,0.807512,0.707819,0.754386,0.869590,0.878884,normal_split_deep_model_metrics.csv,2026.0,NaN,NaN
20,NormalSplit hard-removed OCR+BLIP+BERT+ResNet50 cached-feature MLP,504.0,0.726190,0.724939,0.722022,0.766284,0.743494,0.731278,0.683128,0.706383,0.778424,0.748584,normal_split_rich_cached_mlp_metrics.csv,NaN,NaN,NaN
10,NormalSplit hard-removed Image-only CNN seed123,504.0,0.601190,0.600925,0.617188,0.605364,0.611219,0.584677,0.596708,0.590631,0.636969,0.604965,normal_split_deep_model_metrics.csv,123.0,NaN,NaN
15,NormalSplit hard-removed Image-only CNN seed2026,504.0,0.563492,0.552210,0.563467,0.697318,0.623288,0.563536,0.419753,0.481132,0.612215,0.585191,normal_split_deep_model_metrics.csv,2026.0,NaN,NaN
5,NormalSplit hard-removed Image-only CNN seed42,504.0,0.559524,0.551839,0.563107,0.666667,0.610526,0.553846,0.444444,0.493151,0.605104,0.587445,normal_split_deep_model_metrics.csv,42.0,NaN,NaN
0,NormalSplit hard-removed Majority baseline,504.0,0.517857,0.341176,0.517857,1.000000,0.682353,0.000000,0.000000,0.000000,0.500000,0.482143,normal_split_text_baseline_metrics.csv,NaN,NaN,NaN
21,NormalSplit hard-removed CLIP ViT-B/32 frozen multimodal fusion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal_split_clip_swin_metrics.csv,NaN,skipped,"AttributeError(""'BaseModelOutputWithPooling' object has no attribute 'norm'"")"